// <auto-generated>
// Generated from var enums(1).xml. No runtime XML IO required.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace UniversalGametypeEditor.Megalo
{
    public static partial class MegaloSchema
    {
        public sealed record FieldDef(string Name, string Type, int Bits);
        public sealed record VariantDef(string Key, string Name, int Id, string IdBits, FieldDef[] Fields);
        public sealed record EnumDef(string Name, int Bits, VariantDef[] Variants);

        // --------------------------------------------------------------
        // Universal section vocabulary. Every MegaloSection subtype is
        // a declarative description of a bit-level region in the stream.
        //
        // GametypeReader walks a top-level layout (ReachMpvrLayout) that
        // covers the whole .bin from after the 94-byte MCC wrapper; the
        // ScriptTailReader reuses these same section types on the
        // post-trigger portion of the megalo script block. Since one
        // vocabulary drives everything, a future writer using the same
        // layout table is guaranteed to be bit-for-bit compatible.
        // --------------------------------------------------------------

        public abstract record MegaloSection(string Name);

        /// Fixed-width zeroed / reserved region.
        public sealed record BlankSection(string Name, int Bits) : MegaloSection(Name);

        /// N-bit count followed by N occurrences of a record description.
        public sealed record CountSection(
            string Name,
            int CountBits,
            MegaloSection[] RecordFields,
            /// Optional: name of a table in DecompileContext.Tables to populate
            /// from this count section (index -> rendered name).
            string? TableKey = null,
            /// Optional: name of the record field whose value is used as the
            /// string table index for this record's display name.
            string? NameFromField = null) : MegaloSection(Name);

        /// Variant selector (N-bit tag + a branch chosen by tag).
        public sealed record VariantSection(
            string Name,
            int TagBits,
            (int Id, string Key, MegaloSection[] Fields)[] Variants) : MegaloSection(Name);

        /// Unsigned integer field.
        public sealed record UIntSection(string Name, int Bits) : MegaloSection(Name);

        /// Signed (two's complement) integer field.
        public sealed record SIntSection(string Name, int Bits) : MegaloSection(Name);

        /// Raw hex region (rendered as hex, not decoded).
        public sealed record HexSection(string Name, int Bits) : MegaloSection(Name);

        /// Reference into the mpvr string table (7 bits Reach, 8 bits H4/H2A).
        public sealed record StringTableRefSection(string Name, int Bits) : MegaloSection(Name);

        /// Hash-compressed language-strings block (mpvr.xml "HCount").
        /// Walkthrough: read CountBits → stringPresent; for each, read
        /// NumLanguages × (1-bit present + ValueBits payload); if
        /// stringPresent > 0 read (ValueBits or ValueBits+1 for team) → m3,
        /// 1-bit d flag, then either m3*8 raw bits (d==0) or a ValueBits
        /// compressed-size followed by m1*8 zlib bytes (d==1).
        public sealed record StringTableSection(
            string Name,
            int ValueBits,
            int CountBits,
            bool IsTeamString = false,
            int NumLanguages = 12) : MegaloSection(Name);

        /// Magic/ASCII string of fixed bit length (e.g. "mpvr" @ 32 bits).
        public sealed record AsciiStringSection(string Name, int Bits) : MegaloSection(Name);

        /// Null-terminated 8-bit ASCII string.
        public sealed record UString8Section(string Name) : MegaloSection(Name);

        /// Null-terminated 16-bit-per-char string.
        public sealed record UString16Section(string Name) : MegaloSection(Name);

        /// Field of type "Enumref:X" — walks the TypeRef system.
        public sealed record EnumRefSection(string Name, string EnumName) : MegaloSection(Name);

        /// Reference to another named MegaloSection layout by key (used to
        /// share PlayerTraits / TeamOptions / LoadoutOptions blocks across
        /// multiple parent containers).
        public sealed record SectionRefSection(string Name, string LayoutKey) : MegaloSection(Name);

        /// Inline group / container — a sequence of child sections with a
        /// group name but no header bits of its own.
        public sealed record GroupSection(string Name, MegaloSection[] Children) : MegaloSection(Name);

        /// Marker for sections where the bit layout is NOT yet empirically
        /// verified against real .bin files. Walker treats these as hard
        /// stops with a diagnostic.
        public sealed record UnverifiedSection(string Name, string Note) : MegaloSection(Name);

        // All enum/union schemas from the XML (RefTypes).
        public static readonly IReadOnlyDictionary<string, EnumDef> Enums;

        // Named reusable RefType layouts from mpvr.xml (PlayerTraits,
        // TeamOptions, LoadoutOptions). Referenced by SectionRefSection.
        public static readonly IReadOnlyDictionary<string, MegaloSection[]> Layouts;

        // Full Reach gametype variant layout from bit 752 of the .bin
        // through WeaponTunings at EOF. Walked by GametypeReader.
        public static readonly MegaloSection[] ReachMpvrLayout;

        // Reach post-trigger script + mpvr tail layout, walked by the
        // ScriptTailReader from the current stream position after the
        // last trigger record.
        public static readonly MegaloSection[] ReachScriptTail;

        // Convenient built-in identifiers for common script keywords (curated subset).
        // Maps script token -> (LeafEnumName, LeafVariantKey)
        public static readonly IReadOnlyDictionary<string, (string EnumName, string VariantKey)> BuiltinLeaf;

        static MegaloSchema()
        {
            var e = new Dictionary<string, EnumDef>(StringComparer.OrdinalIgnoreCase)
            {
                ["VarType"] = new EnumDef("VarType", 3, new VariantDef[]
                {
                    new VariantDef("NumericVar", "NumericVar", 0, "000", new FieldDef[]
                    {
                        new FieldDef("NumType", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("PlayerVar", "PlayerVar", 1, "001", new FieldDef[]
                    {
                        new FieldDef("PlayerType", "Enumref:PlayerTypeRef", 0),
                    }),
                    new VariantDef("ObjectVar", "ObjectVar", 2, "010", new FieldDef[]
                    {
                        new FieldDef("ObjType", "Enumref:ObjectTypeRef", 0),
                    }),
                    new VariantDef("TeamVar", "TeamVar", 3, "011", new FieldDef[]
                    {
                        new FieldDef("TeamType", "Enumref:TeamTypeRef", 0),
                    }),
                    new VariantDef("TimerVar", "TimerVar", 4, "100", new FieldDef[]
                    {
                        new FieldDef("TimerType", "Enumref:TimerTypeRef", 0),
                    }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 5, "101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110", "Unlabelled·", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["NumericTypeRef"] = new EnumDef("NumericTypeRef", 6, new VariantDef[]
                {
                    new VariantDef("Int16", "Int16", 0, "000000", new FieldDef[]
                    {
                        new FieldDef("Int16", "Int", 16),
                    }),
                    new VariantDef("Player.Number", "Player.Number", 1, "000001", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("PlayerNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playernumbers", 3),
                    }),
                    new VariantDef("Object.Number", "Object.Number", 2, "000010", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("ObjectNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectnumbers", 3),
                    }),
                    new VariantDef("Team.Number", "Team.Number", 3, "000011", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("TeamNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamnumbers", 3),
                    }),
                    new VariantDef("Global.Number", "Global.Number", 4, "000100", new FieldDef[]
                    {
                        new FieldDef("GlobalNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/GlobalVars/globalnumbers", 4),
                    }),
                    new VariantDef("ScriptOption", "ScriptOption", 5, "000101", new FieldDef[]
                    {
                        new FieldDef("Option", "Ref0:Gametype/base/mpvr/ScriptOptions", 4),
                    }),
                    new VariantDef("Object.SpawnSeq", "Object.SpawnSeq", 6, "000110", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                    }),
                    new VariantDef("Team.Score", "Team.Score", 7, "000111", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                    }),
                    new VariantDef("Player.Score", "Player.Score", 8, "001000", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("Player.Money·", "Player.Money·", 9, "001001", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("Player.Rating", "Player.Rating", 10, "001010", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("Player.Stat", "Player.Stat", 11, "001011", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Statistic", "Ref0:Gametype/base/mpvr/megl/playerstats", 2),
                    }),
                    new VariantDef("Team.Stat", "Team.Stat", 12, "001100", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Statistic", "Ref0:Gametype/base/mpvr/megl/playerstats", 2),
                    }),
                    new VariantDef("CurrentRound", "CurrentRound", 13, "001101", new FieldDef[]
                    { }),
                    new VariantDef("SymmetricMode", "SymmetricMode", 14, "001110", new FieldDef[]
                    { }),
                    new VariantDef("SymmetricModeWritable", "SymmetricModeWritable", 15, "001111", new FieldDef[]
                    { }),
                    new VariantDef("ScoreToWin", "ScoreToWin", 16, "010000", new FieldDef[]
                    { }),
                    new VariantDef("Fireteams Enabled", "Fireteams Enabled", 17, "010001", new FieldDef[]
                    { }),
                    new VariantDef("Teams Enabled", "Teams Enabled", 18, "010010", new FieldDef[]
                    { }),
                    new VariantDef("Round Time Limit", "Round Time Limit", 19, "010011", new FieldDef[]
                    { }),
                    new VariantDef("Round Limit", "Round Limit", 20, "010100", new FieldDef[]
                    { }),
                    new VariantDef("Perfection Enabled", "Perfection Enabled", 21, "010101", new FieldDef[]
                    { }),
                    new VariantDef("Early Victory Win Count", "Early Victory Win Count", 22, "010110", new FieldDef[]
                    { }),
                    new VariantDef("Sudden Death Time Limit", "Sudden Death Time Limit", 23, "010111", new FieldDef[]
                    { }),
                    new VariantDef("Grace Period Time Limit", "Grace Period Time Limit", 24, "011000", new FieldDef[]
                    { }),
                    new VariantDef("Player.Lives", "Player.Lives", 25, "011001", new FieldDef[]
                    { }),
                    new VariantDef("Team.Lives", "Team.Lives", 26, "011010", new FieldDef[]
                    { }),
                    new VariantDef("RespawnTime", "RespawnTime", 27, "011011", new FieldDef[]
                    { }),
                    new VariantDef("Suicide Respawn Penalty", "Suicide Respawn Penalty", 28, "011100", new FieldDef[]
                    { }),
                    new VariantDef("Betrayal Respawn Penalty", "Betrayal Respawn Penalty", 29, "011101", new FieldDef[]
                    { }),
                    new VariantDef("Respawn Growth Time", "Respawn Growth Time", 30, "011110", new FieldDef[]
                    { }),
                    new VariantDef("Initial Loadout Selection Time", "Initial Loadout Selection Time", 31, "011111", new FieldDef[]
                    { }),
                    new VariantDef("Respawn Traits Duration", "Respawn Traits Duration", 32, "100000", new FieldDef[]
                    { }),
                    new VariantDef("Friendly Fire Enabled", "Friendly Fire Enabled", 33, "100001", new FieldDef[]
                    { }),
                    new VariantDef("Betrayal Booting Enabled", "Betrayal Booting Enabled", 34, "100010", new FieldDef[]
                    { }),
                    new VariantDef("Enemy Voice Enabled", "Enemy Voice Enabled", 35, "100011", new FieldDef[]
                    { }),
                    new VariantDef("Open Channel Voice Enabled", "Open Channel Voice Enabled", 36, "100100", new FieldDef[]
                    { }),
                    new VariantDef("Dead Player Voice Enabled", "Dead Player Voice Enabled", 37, "100101", new FieldDef[]
                    { }),
                    new VariantDef("Grenades on Map", "Grenades on Map", 38, "100110", new FieldDef[]
                    { }),
                    new VariantDef("Indestructible Vehicles Enabled", "Indestructible Vehicles Enabled", 39, "100111", new FieldDef[]
                    { }),
                    new VariantDef("Red Traits Duration", "Red Traits Duration", 40, "101000", new FieldDef[]
                    { }),
                    new VariantDef("Blue Traits Duration", "Blue Traits Duration", 41, "101001", new FieldDef[]
                    { }),
                    new VariantDef("Yellow Traits Duration", "Yellow Traits Duration", 42, "101010", new FieldDef[]
                    { }),
                    new VariantDef("Object Death Damage Type", "Object Death Damage Type", 43, "101011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 44, "101100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#101101", "Unlabelled·", 45, "101101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#101110", "Unlabelled·", 46, "101110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#101111", "Unlabelled·", 47, "101111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110000", "Unlabelled·", 48, "110000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110001", "Unlabelled·", 49, "110001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110010", "Unlabelled·", 50, "110010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110011", "Unlabelled·", 51, "110011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110100", "Unlabelled·", 52, "110100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110101", "Unlabelled·", 53, "110101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110110", "Unlabelled·", 54, "110110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#110111", "Unlabelled·", 55, "110111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111000", "Unlabelled·", 56, "111000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111001", "Unlabelled·", 57, "111001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111010", "Unlabelled·", 58, "111010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111011", "Unlabelled·", 59, "111011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111100", "Unlabelled·", 60, "111100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111101", "Unlabelled·", 61, "111101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111110", "Unlabelled·", 62, "111110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111111", "Unlabelled·", 63, "111111", new FieldDef[]
                    { }),
                }),
                ["PlayerTypeRef"] = new EnumDef("PlayerTypeRef", 2, new VariantDef[]
                {
                    new VariantDef("Player", "Player", 0, "00", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("Player.Player", "Player.Player", 1, "01", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Player.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playerplayers", 2),
                    }),
                    new VariantDef("Object.Player", "Object.Player", 2, "10", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("Object.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectplayers", 2),
                    }),
                    new VariantDef("Team.Player", "Team.Player", 3, "11", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Team.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamplayers", 2),
                    }),
                }),
                ["ObjectTypeRef"] = new EnumDef("ObjectTypeRef", 3, new VariantDef[]
                {
                    new VariantDef("ObjectRef", "ObjectRef", 0, "000", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                    }),
                    new VariantDef("Player.Object", "Player.Object", 1, "001", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Player.Object", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playerobjects", 2),
                    }),
                    new VariantDef("Object.Object", "Object.Object", 2, "010", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("Object.Object", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectobjects", 2),
                    }),
                    new VariantDef("Team.Object", "Team.Object", 3, "011", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Team.Object", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamobjects", 3),
                    }),
                    new VariantDef("Player.Biped", "Player.Biped", 4, "100", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("Player.Player.Biped", "Player.Player.Biped", 5, "101", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Player.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playerplayers", 2),
                    }),
                    new VariantDef("Object.Player.Biped", "Object.Player.Biped", 6, "110", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("Object.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectplayers", 2),
                    }),
                    new VariantDef("Team.Player.Biped", "Team.Player.Biped", 7, "111", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Team.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamplayers", 2),
                    }),
                }),
                ["TeamTypeRef"] = new EnumDef("TeamTypeRef", 3, new VariantDef[]
                {
                    new VariantDef("Team", "Team", 0, "000", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                    }),
                    new VariantDef("Player.Team", "Player.Team", 1, "001", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Player.Team", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playerteams", 2),
                    }),
                    new VariantDef("Object.Team", "Object.Team", 2, "010", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("Object.Team", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectteams", 1),
                    }),
                    new VariantDef("Team.Team", "Team.Team", 3, "011", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Team.Team", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamteams", 2),
                    }),
                    new VariantDef("PlayersTeam", "PlayersTeam", 4, "100", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                    }),
                    new VariantDef("ObjectsTeam", "ObjectsTeam", 5, "101", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                    }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["TimerTypeRef"] = new EnumDef("TimerTypeRef", 3, new VariantDef[]
                {
                    new VariantDef("Timer", "Timer", 0, "000", new FieldDef[]
                    {
                        new FieldDef("Timer", "Ref0:Gametype/base/mpvr/megl/MegaloVars/GlobalVars/globaltimers", 3),
                    }),
                    new VariantDef("Player.Timer", "Player.Timer", 1, "001", new FieldDef[]
                    {
                        new FieldDef("Player", "Enumref:PlayerRef", 0),
                        new FieldDef("Player.Timer", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playertimers", 2),
                    }),
                    new VariantDef("Team.Timer", "Team.Timer", 2, "010", new FieldDef[]
                    {
                        new FieldDef("Team", "Enumref:TeamRef", 0),
                        new FieldDef("Team.Timer", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamtimers", 2),
                    }),
                    new VariantDef("Object.Timer", "Object.Timer", 3, "011", new FieldDef[]
                    {
                        new FieldDef("Object", "Enumref:ObjectRef", 0),
                        new FieldDef("Object.Timer", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objecttimers", 2),
                    }),
                    new VariantDef("GameRoundTimer", "GameRoundTimer", 4, "100", new FieldDef[]
                    { }),
                    new VariantDef("SuddenDeathTimer", "SuddenDeathTimer", 5, "101", new FieldDef[]
                    { }),
                    new VariantDef("OvertimeTimer·", "OvertimeTimer·", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["NumericRef"] = new EnumDef("NumericRef", 4, new VariantDef[]
                {
                    new VariantDef("GlobalNum[0]", "GlobalNum[0]", 0, "0000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[1]", "GlobalNum[1]", 1, "0001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[2]", "GlobalNum[2]", 2, "0010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[3]", "GlobalNum[3]", 3, "0011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[4]", "GlobalNum[4]", 4, "0100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[5]", "GlobalNum[5]", 5, "0101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[6]", "GlobalNum[6]", 6, "0110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[7]", "GlobalNum[7]", 7, "0111", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[8]", "GlobalNum[8]", 8, "1000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[9]", "GlobalNum[9]", 9, "1001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[10]", "GlobalNum[10]", 10, "1010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[11]", "GlobalNum[11]", 11, "1011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[12]", "GlobalNum[12]", 12, "1100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[13]", "GlobalNum[13]", 13, "1101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[14]", "GlobalNum[14]", 14, "1110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalNum[15]", "GlobalNum[15]", 15, "1111", new FieldDef[]
                    { }),
                }),
                ["PlayerRef"] = new EnumDef("PlayerRef", 5, new VariantDef[]
                {
                    new VariantDef("NoPlayer", "NoPlayer", 0, "00000", new FieldDef[]
                    { }),
                    new VariantDef("Player0", "Player0", 1, "00001", new FieldDef[]
                    { }),
                    new VariantDef("Player1", "Player1", 2, "00010", new FieldDef[]
                    { }),
                    new VariantDef("Player2", "Player2", 3, "00011", new FieldDef[]
                    { }),
                    new VariantDef("Player3", "Player3", 4, "00100", new FieldDef[]
                    { }),
                    new VariantDef("Player4", "Player4", 5, "00101", new FieldDef[]
                    { }),
                    new VariantDef("Player5", "Player5", 6, "00110", new FieldDef[]
                    { }),
                    new VariantDef("Player6", "Player6", 7, "00111", new FieldDef[]
                    { }),
                    new VariantDef("Player7", "Player7", 8, "01000", new FieldDef[]
                    { }),
                    new VariantDef("Player8", "Player8", 9, "01001", new FieldDef[]
                    { }),
                    new VariantDef("Player9", "Player9", 10, "01010", new FieldDef[]
                    { }),
                    new VariantDef("Player10", "Player10", 11, "01011", new FieldDef[]
                    { }),
                    new VariantDef("Player11", "Player11", 12, "01100", new FieldDef[]
                    { }),
                    new VariantDef("Player12", "Player12", 13, "01101", new FieldDef[]
                    { }),
                    new VariantDef("Player13", "Player13", 14, "01110", new FieldDef[]
                    { }),
                    new VariantDef("Player14", "Player14", 15, "01111", new FieldDef[]
                    { }),
                    new VariantDef("Player15", "Player15", 16, "10000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[0]", "GlobalPlayer[0]", 17, "10001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[1]", "GlobalPlayer[1]", 18, "10010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[2]", "GlobalPlayer[2]", 19, "10011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[3]", "GlobalPlayer[3]", 20, "10100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[4]", "GlobalPlayer[4]", 21, "10101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[5]", "GlobalPlayer[5]", 22, "10110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[6]", "GlobalPlayer[6]", 23, "10111", new FieldDef[]
                    { }),
                    new VariantDef("GlobalPlayer[7]", "GlobalPlayer[7]", 24, "11000", new FieldDef[]
                    { }),
                    new VariantDef("CurrentPlayer", "CurrentPlayer", 25, "11001", new FieldDef[]
                    { }),
                    new VariantDef("HudPlayer", "HudPlayer", 26, "11010", new FieldDef[]
                    { }),
                    new VariantDef("HudTargetPlayer", "HudTargetPlayer", 27, "11011", new FieldDef[]
                    { }),
                    new VariantDef("ObjectKiller", "ObjectKiller", 28, "11100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 29, "11101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11110", "Unlabelled·", 30, "11110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11111", "Unlabelled·", 31, "11111", new FieldDef[]
                    { }),
                }),
                ["ObjectRef"] = new EnumDef("ObjectRef", 5, new VariantDef[]
                {
                    new VariantDef("NoObject", "NoObject", 0, "00000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[0]", "GlobalObject[0]", 1, "00001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[1]", "GlobalObject[1]", 2, "00010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[2]", "GlobalObject[2]", 3, "00011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[3]", "GlobalObject[3]", 4, "00100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[4]", "GlobalObject[4]", 5, "00101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[5]", "GlobalObject[5]", 6, "00110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[6]", "GlobalObject[6]", 7, "00111", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[7]", "GlobalObject[7]", 8, "01000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[8]", "GlobalObject[8]", 9, "01001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[9]", "GlobalObject[9]", 10, "01010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[10]", "GlobalObject[10]", 11, "01011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[11]", "GlobalObject[11]", 12, "01100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[12]", "GlobalObject[12]", 13, "01101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[13]", "GlobalObject[13]", 14, "01110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[14]", "GlobalObject[14]", 15, "01111", new FieldDef[]
                    { }),
                    new VariantDef("GlobalObject[15]", "GlobalObject[15]", 16, "10000", new FieldDef[]
                    { }),
                    new VariantDef("CurrentObject", "CurrentObject", 17, "10001", new FieldDef[]
                    { }),
                    new VariantDef("TargetObject", "TargetObject", 18, "10010", new FieldDef[]
                    { }),
                    new VariantDef("KilledObject", "KilledObject", 19, "10011", new FieldDef[]
                    { }),
                    new VariantDef("KillerObject", "KillerObject", 20, "10100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 21, "10101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#10110", "Unlabelled·", 22, "10110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#10111", "Unlabelled·", 23, "10111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11000", "Unlabelled·", 24, "11000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11001", "Unlabelled·", 25, "11001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11010", "Unlabelled·", 26, "11010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11011", "Unlabelled·", 27, "11011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11100", "Unlabelled·", 28, "11100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11101", "Unlabelled·", 29, "11101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11110", "Unlabelled·", 30, "11110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11111", "Unlabelled·", 31, "11111", new FieldDef[]
                    { }),
                }),
                ["TeamRef"] = new EnumDef("TeamRef", 5, new VariantDef[]
                {
                    new VariantDef("NoTeam", "NoTeam", 0, "00000", new FieldDef[]
                    { }),
                    new VariantDef("Team0", "Team0", 1, "00001", new FieldDef[]
                    { }),
                    new VariantDef("Team1", "Team1", 2, "00010", new FieldDef[]
                    { }),
                    new VariantDef("Team2", "Team2", 3, "00011", new FieldDef[]
                    { }),
                    new VariantDef("Team3", "Team3", 4, "00100", new FieldDef[]
                    { }),
                    new VariantDef("Team4", "Team4", 5, "00101", new FieldDef[]
                    { }),
                    new VariantDef("Team5", "Team5", 6, "00110", new FieldDef[]
                    { }),
                    new VariantDef("Team6", "Team6", 7, "00111", new FieldDef[]
                    { }),
                    new VariantDef("Team7", "Team7", 8, "01000", new FieldDef[]
                    { }),
                    new VariantDef("NeutralTeam", "NeutralTeam", 9, "01001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[0]", "GlobalTeam[0]", 10, "01010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[1]", "GlobalTeam[1]", 11, "01011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[2]", "GlobalTeam[2]", 12, "01100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[3]", "GlobalTeam[3]", 13, "01101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[4]", "GlobalTeam[4]", 14, "01110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[5]", "GlobalTeam[5]", 15, "01111", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[6]", "GlobalTeam[6]", 16, "10000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTeam[7]", "GlobalTeam[7]", 17, "10001", new FieldDef[]
                    { }),
                    new VariantDef("CurrentTeam", "CurrentTeam", 18, "10010", new FieldDef[]
                    { }),
                    new VariantDef("HudPlayer.Team", "HudPlayer.Team", 19, "10011", new FieldDef[]
                    { }),
                    new VariantDef("HudTargetTeam·", "HudTargetTeam·", 20, "10100", new FieldDef[]
                    { }),
                    new VariantDef("UnkTeam21·", "UnkTeam21·", 21, "10101", new FieldDef[]
                    { }),
                    new VariantDef("UnkTeam22·", "UnkTeam22·", 22, "10110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 23, "10111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11000", "Unlabelled·", 24, "11000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11001", "Unlabelled·", 25, "11001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11010", "Unlabelled·", 26, "11010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11011", "Unlabelled·", 27, "11011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11100", "Unlabelled·", 28, "11100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11101", "Unlabelled·", 29, "11101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11110", "Unlabelled·", 30, "11110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11111", "Unlabelled·", 31, "11111", new FieldDef[]
                    { }),
                }),
                ["TimerRef"] = new EnumDef("TimerRef", 3, new VariantDef[]
                {
                    new VariantDef("GlobalTimer[0]", "GlobalTimer[0]", 0, "000", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[1]", "GlobalTimer[1]", 1, "001", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[2]", "GlobalTimer[2]", 2, "010", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[3]", "GlobalTimer[3]", 3, "011", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[4]", "GlobalTimer[4]", 4, "100", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[5]", "GlobalTimer[5]", 5, "101", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[6]", "GlobalTimer[6]", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("GlobalTimer[7]", "GlobalTimer[7]", 7, "111", new FieldDef[]
                    { }),
                }),
                ["GetterOperator"] = new EnumDef("GetterOperator", 3, new VariantDef[]
                {
                    new VariantDef("(<) LessThan", "(<) LessThan", 0, "000", new FieldDef[]
                    { }),
                    new VariantDef("(>) GreaterThan", "(>) GreaterThan", 1, "001", new FieldDef[]
                    { }),
                    new VariantDef("(==)Equals", "(==)Equals", 2, "010", new FieldDef[]
                    { }),
                    new VariantDef("(<=)LessThanEquals", "(<=)LessThanEquals", 3, "011", new FieldDef[]
                    { }),
                    new VariantDef("(>=)GreaterThanEquals", "(>=)GreaterThanEquals", 4, "100", new FieldDef[]
                    { }),
                    new VariantDef("(!=)NotEquals", "(!=)NotEquals", 5, "101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["SetterOperator"] = new EnumDef("SetterOperator", 4, new VariantDef[]
                {
                    new VariantDef("(+=)Add", "(+=)Add", 0, "0000", new FieldDef[]
                    { }),
                    new VariantDef("(-=)Subtract", "(-=)Subtract", 1, "0001", new FieldDef[]
                    { }),
                    new VariantDef("(·=)Multiply", "(·=)Multiply", 2, "0010", new FieldDef[]
                    { }),
                    new VariantDef("(/=)Divide", "(/=)Divide", 3, "0011", new FieldDef[]
                    { }),
                    new VariantDef("(=) Set", "(=) Set", 4, "0100", new FieldDef[]
                    { }),
                    new VariantDef("(%=)Modulo", "(%=)Modulo", 5, "0101", new FieldDef[]
                    { }),
                    new VariantDef("(&=)BinaryAND", "(&=)BinaryAND", 6, "0110", new FieldDef[]
                    { }),
                    new VariantDef("(|=)BinaryOR", "(|=)BinaryOR", 7, "0111", new FieldDef[]
                    { }),
                    new VariantDef("(^=)BinaryXOR", "(^=)BinaryXOR", 8, "1000", new FieldDef[]
                    { }),
                    new VariantDef("(~=)BinaryNOT", "(~=)BinaryNOT", 9, "1001", new FieldDef[]
                    { }),
                    new VariantDef("(<<)LeftShift", "(<<)LeftShift", 10, "1010", new FieldDef[]
                    { }),
                    new VariantDef("(>>)RightShift·", "(>>)RightShift·", 11, "1011", new FieldDef[]
                    { }),
                    new VariantDef("(abs)Absolute", "(abs)Absolute", 12, "1100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 13, "1101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#1110", "Unlabelled·", 14, "1110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#1111", "Unlabelled·", 15, "1111", new FieldDef[]
                    { }),
                }),
                ["Bool"] = new EnumDef("Bool", 1, new VariantDef[]
                {
                    new VariantDef("False", "False", 0, "0", new FieldDef[]
                    { }),
                    new VariantDef("True", "True", 1, "1", new FieldDef[]
                    { }),
                }),
                ["LabelRef"] = new EnumDef("LabelRef", 1, new VariantDef[]
                {
                    new VariantDef("Label", "Label", 0, "0", new FieldDef[]
                    {
                        new FieldDef("ScriptLabel", "Ref0:Gametype/base/mpvr/Labels", 4),
                    }),
                    new VariantDef("None", "None", 1, "1", new FieldDef[]
                    { }),
                }),
                ["Players"] = new EnumDef("Players", 3, new VariantDef[]
                {
                    new VariantDef("No Players", "No Players", 0, "000", new FieldDef[]
                    { }),
                    new VariantDef("Everyone", "Everyone", 1, "001", new FieldDef[]
                    { }),
                    new VariantDef("Allies", "Allies", 2, "010", new FieldDef[]
                    { }),
                    new VariantDef("Enemies", "Enemies", 3, "011", new FieldDef[]
                    { }),
                    new VariantDef("ModPlayer", "ModPlayer", 4, "100", new FieldDef[]
                    {
                        new FieldDef("Target", "Enumref:PlayerTypeRef", 0),
                        new FieldDef("Bool-Include", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("Default·", "Default·", 5, "101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 6, "110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#111", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["WaypointIcon"] = new EnumDef("WaypointIcon", 5, new VariantDef[]
                {
                    new VariantDef("Unlabelled·1", "Unlabelled·1", 0, "00000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·2", "Unlabelled·2", 1, "00001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·3", "Unlabelled·3", 2, "00010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·4", "Unlabelled·4", 3, "00011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·5", "Unlabelled·5", 4, "00100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·6", "Unlabelled·6", 5, "00101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·7", "Unlabelled·7", 6, "00110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·8", "Unlabelled·8", 7, "00111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·9", "Unlabelled·9", 8, "01000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·10", "Unlabelled·10", 9, "01001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·11", "Unlabelled·11", 10, "01010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·12", "Unlabelled·12", 11, "01011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·13", "Unlabelled·13", 12, "01100", new FieldDef[]
                    {
                        new FieldDef("NumberType", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("Unlabelled·14", "Unlabelled·14", 13, "01101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·15", "Unlabelled·15", 14, "01110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·16", "Unlabelled·16", 15, "01111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·17", "Unlabelled·17", 16, "10000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·18", "Unlabelled·18", 17, "10001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·19", "Unlabelled·19", 18, "10010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·20", "Unlabelled·20", 19, "10011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·21", "Unlabelled·21", 20, "10100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·22", "Unlabelled·22", 21, "10101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·23", "Unlabelled·23", 22, "10110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·24", "Unlabelled·24", 23, "10111", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·25", "Unlabelled·25", 24, "11000", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·26", "Unlabelled·26", 25, "11001", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·27", "Unlabelled·27", 26, "11010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·28", "Unlabelled·28", 27, "11011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·29", "Unlabelled·29", 28, "11100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·30", "Unlabelled·30", 29, "11101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·31", "Unlabelled·31", 30, "11110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·32", "Unlabelled·32", 31, "11111", new FieldDef[]
                    { }),
                }),
                ["WaypointPriority"] = new EnumDef("WaypointPriority", 2, new VariantDef[]
                {
                    new VariantDef("Low", "Low", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("Normal", "Normal", 1, "01", new FieldDef[]
                    { }),
                    new VariantDef("High", "High", 2, "10", new FieldDef[]
                    { }),
                    new VariantDef("Blink", "Blink", 3, "11", new FieldDef[]
                    { }),
                }),
                ["ObjectShape"] = new EnumDef("ObjectShape", 2, new VariantDef[]
                {
                    new VariantDef("NoShape", "NoShape", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("Sphere", "Sphere", 1, "01", new FieldDef[]
                    {
                        new FieldDef("Radius", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("Cylinder", "Cylinder", 2, "10", new FieldDef[]
                    {
                        new FieldDef("Radius", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Top", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Bottom", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("Box", "Box", 3, "11", new FieldDef[]
                    {
                        new FieldDef("Width", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Length", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Top", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Bottom", "Enumref:NumericTypeRef", 0),
                    }),
                }),
                ["ObjectTimerIndex"] = new EnumDef("ObjectTimerIndex", 1, new VariantDef[]
                {
                    new VariantDef("Timer", "Timer", 0, "0", new FieldDef[]
                    {
                        new FieldDef("Object.Timer", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objecttimers", 2),
                    }),
                    new VariantDef("None", "None", 1, "1", new FieldDef[]
                    { }),
                }),
                ["TimerRate"] = new EnumDef("TimerRate", 5, new VariantDef[]
                {
                    new VariantDef("0%", "0%", 0, "00000", new FieldDef[]
                    { }),
                    new VariantDef("-10%", "-10%", 1, "00001", new FieldDef[]
                    { }),
                    new VariantDef("-25%", "-25%", 2, "00010", new FieldDef[]
                    { }),
                    new VariantDef("-50%", "-50%", 3, "00011", new FieldDef[]
                    { }),
                    new VariantDef("-75%", "-75%", 4, "00100", new FieldDef[]
                    { }),
                    new VariantDef("-100%", "-100%", 5, "00101", new FieldDef[]
                    { }),
                    new VariantDef("-125%", "-125%", 6, "00110", new FieldDef[]
                    { }),
                    new VariantDef("-150%", "-150%", 7, "00111", new FieldDef[]
                    { }),
                    new VariantDef("-175%", "-175%", 8, "01000", new FieldDef[]
                    { }),
                    new VariantDef("-200%", "-200%", 9, "01001", new FieldDef[]
                    { }),
                    new VariantDef("-300%", "-300%", 10, "01010", new FieldDef[]
                    { }),
                    new VariantDef("-400%", "-400%", 11, "01011", new FieldDef[]
                    { }),
                    new VariantDef("-500%", "-500%", 12, "01100", new FieldDef[]
                    { }),
                    new VariantDef("-1000%", "-1000%", 13, "01101", new FieldDef[]
                    { }),
                    new VariantDef("10%", "10%", 14, "01110", new FieldDef[]
                    { }),
                    new VariantDef("25%", "25%", 15, "01111", new FieldDef[]
                    { }),
                    new VariantDef("50%", "50%", 16, "10000", new FieldDef[]
                    { }),
                    new VariantDef("75%", "75%", 17, "10001", new FieldDef[]
                    { }),
                    new VariantDef("100%", "100%", 18, "10010", new FieldDef[]
                    { }),
                    new VariantDef("125%", "125%", 19, "10011", new FieldDef[]
                    { }),
                    new VariantDef("150%", "150%", 20, "10100", new FieldDef[]
                    { }),
                    new VariantDef("175%", "175%", 21, "10101", new FieldDef[]
                    { }),
                    new VariantDef("200%", "200%", 22, "10110", new FieldDef[]
                    { }),
                    new VariantDef("300%", "300%", 23, "10111", new FieldDef[]
                    { }),
                    new VariantDef("400%", "400%", 24, "11000", new FieldDef[]
                    { }),
                    new VariantDef("500%", "500%", 25, "11001", new FieldDef[]
                    { }),
                    new VariantDef("1000%", "1000%", 26, "11010", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 27, "11011", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11100", "Unlabelled·", 28, "11100", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11101", "Unlabelled·", 29, "11101", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11110", "Unlabelled·", 30, "11110", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·#11111", "Unlabelled·", 31, "11111", new FieldDef[]
                    { }),
                }),
                ["IncidentPlayers"] = new EnumDef("IncidentPlayers", 2, new VariantDef[]
                {
                    new VariantDef("Team", "Team", 0, "00", new FieldDef[]
                    {
                        new FieldDef("TeamType", "Enumref:TeamTypeRef", 0),
                    }),
                    new VariantDef("Players", "Players", 1, "01", new FieldDef[]
                    {
                        new FieldDef("PlayerType", "Enumref:PlayerTypeRef", 0),
                    }),
                    new VariantDef("AllPlayers", "AllPlayers", 2, "10", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 3, "11", new FieldDef[]
                    { }),
                }),
                ["PickupMode"] = new EnumDef("PickupMode", 2, new VariantDef[]
                {
                    new VariantDef("Normal", "Normal", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("HoldAction", "HoldAction", 1, "01", new FieldDef[]
                    { }),
                    new VariantDef("Automatic", "Automatic", 2, "10", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 3, "11", new FieldDef[]
                    { }),
                }),
                ["WidgetRef"] = new EnumDef("WidgetRef", 1, new VariantDef[]
                {
                    new VariantDef("Widget", "Widget", 0, "0", new FieldDef[]
                    {
                        new FieldDef("ScriptWidget", "Ref0:Gametype/base/mpvr/megl/hudwidgets", 2),
                    }),
                    new VariantDef("NoWidget", "NoWidget", 1, "1", new FieldDef[]
                    { }),
                }),
                ["WidgetMeter"] = new EnumDef("WidgetMeter", 2, new VariantDef[]
                {
                    new VariantDef("None", "None", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("Fraction", "Fraction", 1, "01", new FieldDef[]
                    {
                        new FieldDef("Current", "Enumref:NumericTypeRef", 0),
                        new FieldDef("Maximum", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("Timer", "Timer", 2, "10", new FieldDef[]
                    {
                        new FieldDef("TimerRef", "Enumref:TimerTypeRef", 0),
                    }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 3, "11", new FieldDef[]
                    { }),
                }),
                ["GrenadeType"] = new EnumDef("GrenadeType", 1, new VariantDef[]
                {
                    new VariantDef("Frag", "Frag", 0, "0", new FieldDef[]
                    { }),
                    new VariantDef("Plasma", "Plasma", 1, "1", new FieldDef[]
                    { }),
                }),
                ["GiveWeaponMode"] = new EnumDef("GiveWeaponMode", 2, new VariantDef[]
                {
                    new VariantDef("Primary", "Primary", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("Secondary", "Secondary", 1, "01", new FieldDef[]
                    { }),
                    new VariantDef("Force", "Force", 2, "10", new FieldDef[]
                    { }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 3, "11", new FieldDef[]
                    { }),
                }),
                ["DropWeaponMode"] = new EnumDef("DropWeaponMode", 1, new VariantDef[]
                {
                    new VariantDef("Primary", "Primary", 0, "0", new FieldDef[]
                    { }),
                    new VariantDef("Secondary", "Secondary", 1, "1", new FieldDef[]
                    { }),
                }),
                ["ObjectPlayerIndex"] = new EnumDef("ObjectPlayerIndex", 1, new VariantDef[]
                {
                    new VariantDef("PlayerIndex", "PlayerIndex", 0, "0", new FieldDef[]
                    {
                        new FieldDef("Object.Player", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectplayers", 2),
                    }),
                    new VariantDef("None", "None", 1, "1", new FieldDef[]
                    { }),
                }),
                ["StringToken"] = new EnumDef("StringToken", 3, new VariantDef[]
                {
                    new VariantDef("None", "None", 0, "000", new FieldDef[]
                    { }),
                    new VariantDef("PlayerVar", "PlayerVar", 1, "001", new FieldDef[]
                    {
                        new FieldDef("PlayerType", "Enumref:PlayerTypeRef", 0),
                    }),
                    new VariantDef("TeamVar", "TeamVar", 2, "010", new FieldDef[]
                    {
                        new FieldDef("TeamType", "Enumref:TeamTypeRef", 0),
                    }),
                    new VariantDef("ObjectVar", "ObjectVar", 3, "011", new FieldDef[]
                    {
                        new FieldDef("ObjectType", "Enumref:ObjectTypeRef", 0),
                    }),
                    new VariantDef("NumericVar", "NumericVar", 4, "100", new FieldDef[]
                    {
                        new FieldDef("NumberType", "Enumref:NumericTypeRef", 0),
                    }),
                    new VariantDef("TimerVar", "TimerVar", 5, "101", new FieldDef[]
                    {
                        new FieldDef("TimerType", "Enumref:TimerTypeRef", 0),
                    }),
                    new VariantDef("TimerVarAswell", "TimerVarAswell", 6, "110", new FieldDef[]
                    {
                        new FieldDef("TimerType", "Enumref:TimerTypeRef", 0),
                    }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 7, "111", new FieldDef[]
                    { }),
                }),
                ["StringVars2"] = new EnumDef("StringVars2", 2, new VariantDef[]
                {
                    new VariantDef("None", "None", 0, "00", new FieldDef[]
                    { }),
                    new VariantDef("Vars1", "Vars1", 1, "01", new FieldDef[]
                    {
                        new FieldDef("Token", "Enumref:StringToken", 0),
                    }),
                    new VariantDef("Vars2", "Vars2", 2, "10", new FieldDef[]
                    {
                        new FieldDef("Token1", "Enumref:StringToken", 0),
                        new FieldDef("Token2", "Enumref:StringToken", 0),
                    }),
                    new VariantDef("Unlabelled·", "Unlabelled·", 3, "11", new FieldDef[]
                    { }),
                }),
            };
            Enums = e;

            // --------------------------------------------------------------
            // Reach post-trigger tail layout.
            //
            // Everything above the first UnverifiedSection has a known bit
            // layout (sourced from either mpvr.xml, the legacy working
            // ReadScriptOptions/ReadStrings/ReadGame/ReadMap/ReadPlayerRatings
            // readers, or the Labels section grammar in mpvr.xml).
            //
            // The MegaloVars globals pool widths are NOT yet empirically
            // verified. Rather than guess and silently corrupt the rest of
            // the stream, we plant an UnverifiedSection that forces the
            // decoder to stop and emit a diagnostic identifying the exact
            // point where the layout spec runs out. That way the first
            // real-.bin test will surface the missing widths at a single,
            // specific location we can then fix in one place.
            //
            // Order per mpvr.xml:
            //   megl  → globals (script vars)
            //         → MegaloVars sub-pools
            //         → hud widgets / stats / traits / options / strings
            //         → game / map / player ratings / reserved blanks
            //   after megl →
            //     requiredobjects(224)  [blank]
            //     unknown1824           [blank]
            //     Labels                [count 5, per-label StringID + flag fields + MapMinimum]
            //     unknown26             [blank]
            //     WeaponTunings
            // --------------------------------------------------------------

            // Per-entry record shapes for global variable pools.
            // Sourced from community Reach megalo documentation +
            // cross-referenced against the compiler's intent (not its
            // buggy emission widths). Networking priority is the common
            // 2-bit "locality" field on every variable.
            var globalNumberRec = new MegaloSection[]
            {
                new SIntSection("InitialValue", 16),
                new UIntSection("NetworkPriority", 2),
            };
            var globalTimerRec = new MegaloSection[]
            {
                new SIntSection("InitialValue", 16),
                new UIntSection("NetworkPriority", 2),
            };
            var globalTeamRec = new MegaloSection[]
            {
                new UIntSection("InitialTeam", 4),
                new UIntSection("NetworkPriority", 2),
            };
            var globalPlayerRec = new MegaloSection[]
            {
                new UIntSection("NetworkPriority", 2),
            };
            var globalObjectRec = new MegaloSection[]
            {
                new UIntSection("NetworkPriority", 2),
            };

            ReachScriptTail = new MegaloSection[]
            {
                // ---- Script variable globals (after triggers) ----
                new CountSection("GlobalNumbers", 4, globalNumberRec),
                new CountSection("GlobalTimers", 4, globalTimerRec),
                new CountSection("GlobalTeams", 4, globalTeamRec),
                new CountSection("GlobalPlayers", 4, globalPlayerRec),
                new CountSection("GlobalObjects", 5, globalObjectRec),

                // ---- MegaloVars sub-pools, scoped to player/object/team ----
                // Per the compiler's ProcessGlobalVariables emission order,
                // these are 15 sub-pools with an all-zero body when empty.
                // Counts match mpvr.xml "Ref0" pool widths.
                new CountSection("playernumbers", 4, globalNumberRec),
                new CountSection("playertimers", 3, globalTimerRec),
                new CountSection("playerteams",  3, globalTeamRec),
                new CountSection("playerplayers",3, globalPlayerRec),
                new CountSection("playerobjects",3, globalObjectRec),

                new CountSection("objectnumbers", 4, globalNumberRec),
                new CountSection("objecttimers",  3, globalTimerRec),
                new CountSection("objectteams",   2, globalTeamRec),
                new CountSection("objectplayers", 3, globalPlayerRec),
                new CountSection("objectobjects", 3, globalObjectRec),

                new CountSection("teamnumbers", 4, globalNumberRec),
                new CountSection("teamtimers",  3, globalTimerRec),
                new CountSection("teamteams",   3, globalTeamRec),
                new CountSection("teamplayers", 3, globalPlayerRec),
                new CountSection("teamobjects", 3, globalObjectRec),

                // HUD widgets + script stats + script widgets are not yet
                // schema-described; this UnverifiedSection hard-stops so
                // real-.bin testing points at the exact boundary to fix.
                new UnverifiedSection(
                    "HudWidgetsAndStats",
                    "HUD widgets / script stats / script widgets post-MegaloVars. "
                    + "Need empirical widths — compiler doesn't emit them, mpvr.xml has no entry."),
            };

            BuiltinLeaf = new Dictionary<string, (string EnumName, string VariantKey)>(StringComparer.OrdinalIgnoreCase)
            {
                ["no_object"] = ("ObjectRef", "NoObject"),
                ["current_object"] = ("ObjectRef", "CurrentObject"),
                ["target_object"] = ("ObjectRef", "TargetObject"),
                ["killed_object"] = ("ObjectRef", "KilledObject"),
                ["killer_object"] = ("ObjectRef", "KillerObject"),
                ["no_player"] = ("PlayerRef", "NoPlayer"),
                ["current_player"] = ("PlayerRef", "CurrentPlayer"),
                ["hud_player"] = ("PlayerRef", "HudPlayer"),
                ["hud_target_player"] = ("PlayerRef", "HudTargetPlayer"),
                ["object_killer"] = ("PlayerRef", "ObjectKiller"),
                ["no_team"] = ("TeamRef", "NoTeam"),
                ["current_team"] = ("TeamRef", "CurrentTeam"),
                ["neutral_team"] = ("TeamRef", "NeutralTeam"),
            };

            // --------------------------------------------------------------
            // Named reusable layouts, referenced by SectionRefSection from
            // within parent containers. These map to mpvr.xml <RefTypes>.
            // --------------------------------------------------------------
            var layouts = new Dictionary<string, MegaloSection[]>(StringComparer.OrdinalIgnoreCase);

            layouts["PlayerTraits"] = new MegaloSection[]
            {
                new UIntSection("DamageResistance", 4),
                new UIntSection("Healthmultiplyer", 3),
                new UIntSection("Healthregenrate", 4),
                new UIntSection("ShieldMultiplyer", 3),
                new UIntSection("ShieldRegenrate", 4),
                new UIntSection("Overshieldregenrate", 4),
                new UIntSection("HeadshotImmunity", 2),
                new UIntSection("shieldvampirism", 3),
                new UIntSection("Assasinationimmunity", 2),
                new UIntSection("invincible", 2),
                new UIntSection("WeaponDamagemultiplier", 4),
                new UIntSection("MeleeDamagemultiplier", 4),
                new UIntSection("Primaryweapon", 8),
                new UIntSection("Secondaryweapon", 8),
                new UIntSection("Grenades", 4),
                new UIntSection("Infiniteammo", 2),
                new UIntSection("Grenaderegen", 2),
                new UIntSection("WeaponPickup", 2),
                new UIntSection("AbilityUsage", 2),
                new UIntSection("Abilitiesdropondeath", 2),
                new UIntSection("InfiniteAbility", 2),
                new UIntSection("ArmorAbility", 8),
                new UIntSection("MovementSpeed", 5),
                new UIntSection("Playergravity", 4),
                new UIntSection("VehicleUse", 4),
                new UIntSection("Unknown", 2),
                new VariantSection("JumpHeight", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "Unchanged", Array.Empty<MegaloSection>()),
                    (1, "Override",  new MegaloSection[] { new UIntSection("JumpHeight", 9) }),
                }),
                new UIntSection("Camo", 3),
                new UIntSection("Visiblewaypoint", 2),
                new UIntSection("VisibleName", 2),
                new UIntSection("Aura", 3),
                new UIntSection("Forcedcolor", 4),
                new UIntSection("Motiontrackermode", 3),
                new UIntSection("MotiontrackerRange", 3),
                new UIntSection("DirectionalDamageindicator", 2),
            };

            layouts["TeamOptions"] = new MegaloSection[]
            {
                new UIntSection("TertiarycolorOverride", 1),
                new UIntSection("SecondarycolorOverride", 1),
                new UIntSection("PrimarycolorOverride", 1),
                new UIntSection("TeamEnabled", 1),
                new StringTableSection("Teamstring", ValueBits: 5, CountBits: 1, IsTeamString: true),
                new UIntSection("InitialDesignator", 4),
                new UIntSection("Elitespecies", 1),
                new HexSection("PrimaryColor", 32),
                new HexSection("SecondaryColor", 32),
                new HexSection("TertiaryColor", 32),
                new UIntSection("FireteamCount", 5),
            };

            layouts["LoadoutOptions"] = new MegaloSection[]
            {
                new UIntSection("LoadoutVisibleingame", 1),
                new VariantSection("LoadoutName", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "True",  new MegaloSection[] { new UIntSection("NameIndex", 7) }),
                    (1, "False", Array.Empty<MegaloSection>()),
                }),
                new UIntSection("PrimaryWeapon", 8),
                new UIntSection("SecondaryWeapon", 8),
                new UIntSection("Armorability", 8),
                new UIntSection("Grenades", 4),
            };

            Layouts = layouts;

            // --------------------------------------------------------------
            // ReachMpvrLayout — full Reach gametype variant layout,
            // walked by GametypeReader from bit 752 of the raw .bin file
            // (i.e. past the 94-byte MCC wrapper) through WeaponTunings.
            //
            // Order and widths are anchored to mpvr.xml, the legacy working
            // ReadBinary code (ReadScriptOptions / ReadStrings / ReadGame /
            // ReadMap / ReadPlayerRatings), and community Reach-megalo docs.
            // Any entry that hasn't been empirically verified against a
            // stock .bin is an UnverifiedSection so the walker hard-stops
            // rather than silently desyncing.
            //
            // H4 / H2A differ in several widths; those live in separate
            // layouts (to be added once Reach is round-tripping cleanly).
            // --------------------------------------------------------------

            ReachMpvrLayout = new MegaloSection[]
            {
                // FileHeader
                new AsciiStringSection("mpvr", 32),
                new UIntSection("megaloversion", 32),
                new UIntSection("Unknown0x2F8", 16),
                new UIntSection("Unknown0x2FA", 16),
                new HexSection("UnknownHash0x2FC", 160),
                new HexSection("Blank0x310", 32),
                new UIntSection("Fileusedsize", 32),
                new UIntSection("Unknown0x318", 2),
                new UIntSection("VariantType", 2),
                new UIntSection("Unknown0x319", 4),
                new UIntSection("Unknown0x31D", 32),
                new UIntSection("Unknown0x31C", 32),
                new UIntSection("FileLength", 32),

                // GametypeHeader
                new HexSection("ID0x48", 64),
                new HexSection("ID0x50", 64),
                new HexSection("ID0x58", 64),
                new HexSection("Blank0x60", 64),
                new BlankSection("UnknownFlags", 9),
                new UIntSection("Unknown_1", 32),
                new UIntSection("Unknown0x1", 8),
                new UIntSection("Blank04", 32),
                new HexSection("TimeStampUint", 32),
                new HexSection("XUID", 64),
                new UString8Section("Gamertag"),
                new BlankSection("Blank041bit", 33),
                new HexSection("EditTimeStampUint", 32),
                new HexSection("EditXUID", 64),
                new UString8Section("EditGamertag"),
                new UIntSection("UnknownFlag1", 1),
                new UString16Section("Title"),
                new UString16Section("Description"),
                new UIntSection("GameIcon", 8),

                // ModeSettings (Reach path — UnknownFlag2 is 1 bit here).
                new UIntSection("UnknownFlag2", 1),
                new UIntSection("Teamsenabled", 1),
                new UIntSection("Resetmaponnewroundunused", 1),
                new UIntSection("Resetplayersonnewroundunused", 1),
                new UIntSection("Perfectionmedalenabled", 1),
                new UIntSection("RoundTimeLimit", 8),
                new UIntSection("NumberOfRounds", 5),
                new UIntSection("RoundsToWin", 4),
                new UIntSection("SuddenDeathTime", 7),
                new UIntSection("GracePeriod", 5),

                // SpawnSettings
                new UIntSection("RespawnOnKills", 1),
                new UIntSection("respawnatlocationunused", 1),
                new UIntSection("respawnwithteammateunused", 1),
                new UIntSection("RespawnSyncwithteam", 1),
                new UIntSection("LivesPerround", 6),
                new UIntSection("TeamLivesPerround", 7),
                new UIntSection("RespawnTime", 8),
                new UIntSection("Suicidepenalty", 8),
                new UIntSection("Betrayalpenalty", 8),
                new UIntSection("RespawnTimegrowth", 4),
                new UIntSection("LoadoutCamTime", 4),
                new UIntSection("Respawntraitsduration", 6),
                new SectionRefSection("RespawnPlayerTraits", "PlayerTraits"),

                // GameSettings
                new UIntSection("EnableObservers", 1),
                new UIntSection("Teamchanging", 2),
                new UIntSection("FriendlyFire", 1),
                new UIntSection("BetrayalBooting", 1),
                new UIntSection("ProximityVoice", 1),
                new UIntSection("Dontrestrictteamvoicechat", 1),
                new UIntSection("allowdeadplayerstotalk", 1),
                new UIntSection("Indestructiblevehicles", 1),
                new UIntSection("turretsonmap", 1),
                new UIntSection("powerupsonmap", 1),
                new UIntSection("abilitiesonmap", 1),
                new UIntSection("shortcutsonmap", 1),
                new UIntSection("grenadesonmap", 1),
                new SectionRefSection("BasePlayerTraits", "PlayerTraits"),
                new UIntSection("WeaponSet", 8),
                new UIntSection("VehicleSet", 8),

                // PowerupTraits
                new SectionRefSection("RedPlayerTraits", "PlayerTraits"),
                new SectionRefSection("BluePlayerTraits", "PlayerTraits"),
                new SectionRefSection("YellowPlayerTraits", "PlayerTraits"),
                new UIntSection("RedPowerupDuration", 7),
                new UIntSection("BluePowerupDuration", 7),
                new UIntSection("YellowPowerupDuration", 7),

                // TeamSettings
                new UIntSection("TeamScoringMethod", 3),
                new UIntSection("PlayerSpecies", 3),
                new UIntSection("DesignatorSwitchtype", 2),
                new SectionRefSection("Team1Options", "TeamOptions"),
                new SectionRefSection("Team2Options", "TeamOptions"),
                new SectionRefSection("Team3Options", "TeamOptions"),
                new SectionRefSection("Team4Options", "TeamOptions"),
                new SectionRefSection("Team5Options", "TeamOptions"),
                new SectionRefSection("Team6Options", "TeamOptions"),
                new SectionRefSection("Team7Options", "TeamOptions"),
                new SectionRefSection("Team8Options", "TeamOptions"),

                // LoadoutPalettes — 30 fixed-position LoadoutOptions, gated by two 1-bit flags.
                new UIntSection("EliteLoadoutsEnabled", 1),
                new UIntSection("SpartanLoadoutsEnabled", 1),
                new SectionRefSection("loadouts01", "LoadoutOptions"),
                new SectionRefSection("loadouts02", "LoadoutOptions"),
                new SectionRefSection("loadouts03", "LoadoutOptions"),
                new SectionRefSection("loadouts04", "LoadoutOptions"),
                new SectionRefSection("loadouts05", "LoadoutOptions"),
                new SectionRefSection("loadouts06", "LoadoutOptions"),
                new SectionRefSection("loadouts07", "LoadoutOptions"),
                new SectionRefSection("loadouts08", "LoadoutOptions"),
                new SectionRefSection("loadouts09", "LoadoutOptions"),
                new SectionRefSection("loadouts10", "LoadoutOptions"),
                new SectionRefSection("loadouts11", "LoadoutOptions"),
                new SectionRefSection("loadouts12", "LoadoutOptions"),
                new SectionRefSection("loadouts13", "LoadoutOptions"),
                new SectionRefSection("loadouts14", "LoadoutOptions"),
                new SectionRefSection("loadouts15", "LoadoutOptions"),
                new SectionRefSection("loadouts16", "LoadoutOptions"),
                new SectionRefSection("loadouts17", "LoadoutOptions"),
                new SectionRefSection("loadouts18", "LoadoutOptions"),
                new SectionRefSection("loadouts19", "LoadoutOptions"),
                new SectionRefSection("loadouts20", "LoadoutOptions"),
                new SectionRefSection("loadouts21", "LoadoutOptions"),
                new SectionRefSection("loadouts22", "LoadoutOptions"),
                new SectionRefSection("loadouts23", "LoadoutOptions"),
                new SectionRefSection("loadouts24", "LoadoutOptions"),
                new SectionRefSection("loadouts25", "LoadoutOptions"),
                new SectionRefSection("loadouts26", "LoadoutOptions"),
                new SectionRefSection("loadouts27", "LoadoutOptions"),
                new SectionRefSection("loadouts28", "LoadoutOptions"),
                new SectionRefSection("loadouts29", "LoadoutOptions"),
                new SectionRefSection("loadouts30", "LoadoutOptions"),

                // --- Pre-megl container sections (mpvr.xml order) ---
                new CountSection("ScriptedPlayerTraits", 5, new MegaloSection[]
                {
                    new StringTableRefSection("String1", 7),
                    new StringTableRefSection("String2", 7),
                    new SectionRefSection("PlayerTraits", "PlayerTraits"),
                }),

                new CountSection("ScriptOptions", 5, new MegaloSection[]
                {
                    new StringTableRefSection("String1", 7),
                    new StringTableRefSection("String2", 7),
                    new VariantSection("ScriptOption", 1, new (int, string, MegaloSection[])[]
                    {
                        (0, "Scriptoption", new MegaloSection[]
                        {
                            new UIntSection("ChildIndex", 3),
                            new CountSection("ScriptOptionChild", 4, new MegaloSection[]
                            {
                                new SIntSection("Value", 10),
                                new StringTableRefSection("String1", 7),
                                new StringTableRefSection("String2", 7),
                            }),
                            new UIntSection("Unknown", 3),
                        }),
                        (1, "Range", new MegaloSection[]
                        {
                            new SIntSection("range1", 10),
                            new SIntSection("range2", 10),
                            new SIntSection("range3", 10),
                            new SIntSection("range4", 10),
                        }),
                    }),
                }),

                // Strings block — main string table + four metastring tables.
                // Populates the string table used to render Labels/Traits names.
                new StringTableSection(
                    "Stringtable",
                    ValueBits: 15, CountBits: 7,
                    IsTeamString: false, NumLanguages: 12),
                new StringTableRefSection("StringNameIndex", 7),
                new StringTableSection("metanameStrings",  ValueBits: 9,  CountBits: 1, NumLanguages: 12),
                new StringTableSection("metadescStrings",  ValueBits: 12, CountBits: 1, NumLanguages: 12),
                new StringTableSection("metagroupStrings", ValueBits: 9,  CountBits: 1, NumLanguages: 12),

                // Game / map perms / player ratings.
                new UIntSection("ActualGameicon", 5),
                new UIntSection("ActualGamecategory", 5),
                new CountSection("mapperms", 6, new MegaloSection[]
                {
                    new HexSection("MapID", 16),
                }),
                new UIntSection("mappermsflip", 1),

                new HexSection("Playerrating-ratingscale", 32),
                new HexSection("Playerrating-kilweight", 32),
                new HexSection("Playerrating-assistweight", 32),
                new HexSection("Playerrating-betrayalweight", 32),
                new HexSection("Playerrating-deathweight", 32),
                new HexSection("Playerrating-normalizebymaxkills", 32),
                new HexSection("Playerrating-base", 32),
                new HexSection("Playerrating-range", 32),
                new HexSection("Playerrating-lossscalar", 32),
                new HexSection("Playerrating-customstat0", 32),
                new HexSection("Playerrating-customstat1", 32),
                new HexSection("Playerrating-customstat2", 32),
                new HexSection("Playerrating-customstat3", 32),
                new HexSection("Playerrating-expansion0", 32),
                new HexSection("Playerrating-expansion1", 32),
                new UIntSection("showplayerratings", 1),

                new BlankSection("unknown2643", 2642),

                // megl — script block handed to ScriptDecompiler; see
                // GametypeReader's UnverifiedSection handler for the routing.
                new UnverifiedSection(
                    "megl",
                    "Megalo script block — parsed by ScriptDecompiler. "
                    + "GametypeReader hands off at this boundary."),

                // requiredobjects + reserved — after megl per mpvr.xml.
                new BlankSection("requiredobjects", 224),
                new BlankSection("unknown1824", 1824),

                // Forge labels.
                new CountSection(
                    Name: "Labels",
                    CountBits: 5,
                    TableKey: "Gametype/base/mpvr/Labels",
                    NameFromField: "StringID",
                    RecordFields: new MegaloSection[]
                    {
                        new StringTableRefSection("StringID", 7),
                        new VariantSection("usenumber", 1, new (int, string, MegaloSection[])[]
                        {
                            (0, "Null",   Array.Empty<MegaloSection>()),
                            (1, "InUse",  new MegaloSection[] { new SIntSection("Number", 16) }),
                        }),
                        new VariantSection("useteamtype", 1, new (int, string, MegaloSection[])[]
                        {
                            (0, "Null",   Array.Empty<MegaloSection>()),
                            (1, "InUse",  new MegaloSection[] { new UIntSection("Team", 4) }),
                        }),
                        new VariantSection("useobjectype", 1, new (int, string, MegaloSection[])[]
                        {
                            (0, "Null",   Array.Empty<MegaloSection>()),
                            (1, "InUse",  new MegaloSection[] { new UIntSection("Objecttype", 12) }),
                        }),
                        new UIntSection("MapMinimum", 7),
                    }),

                new BlankSection("unknown26", 26),

                // WeaponTunings
                new UIntSection("FullAutomagnum", 1),
                new UIntSection("MustHaveEnergySwordToBlock", 1),
                new UIntSection("EnableActiveCamoModifiers", 1),
                new UIntSection("ArmorLockCanBeStuck", 1),
                new UIntSection("Armorlockdoesntshednades", 1),
                new UIntSection("ShieldBleedthrough", 1),
                new BlankSection("PrecisionWeaponBloom", 8),
                new BlankSection("ArmorLockDamageDrain", 8),
                new BlankSection("ArmorLockDamageDrainLimit", 8),
                new BlankSection("ActivecamoEnergyDraincurveMax", 8),
                new BlankSection("ActivecamoEnergyDraincurveMin", 8),
                new BlankSection("MagnumDamage", 8),
                new BlankSection("MagnumFireDelayModifier", 8),
            };
        }

        public static bool TryGetEnum(string enumName, out EnumDef def)
            => Enums.TryGetValue(enumName, out def!);

        public static bool TryGetVariant(string enumName, string variantKey, out VariantDef def)
        {
            def = null!;
            if (!Enums.TryGetValue(enumName, out var ed)) return false;
            foreach (var v in ed.Variants)
            {
                if (string.Equals(v.Key, variantKey, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(v.Name, variantKey, StringComparison.OrdinalIgnoreCase))
                {
                    def = v;
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Helper: return the (EnumName, VariantKey) for a built-in leaf identifier like 'current_object'.
        /// These are *leaf refs* such as ObjectRef/PlayerRef/etc (not TypeRef/VarType).
        /// </summary>
        public static bool TryResolveBuiltinLeaf(string token, out string enumName, out string variantKey)
        {
            enumName = variantKey = string.Empty;
            if (!BuiltinLeaf.TryGetValue(token, out var t)) return false;
            enumName = t.EnumName;
            variantKey = t.VariantKey;
            return true;
        }
    }
}