// <auto-generated>
// Parallel H2A schema definitions, ported from Megalograph's
// XMLs/Halo 2A/mpvr.xml and XMLs/Halo 2A/var enums.xml. This file
// extends the MegaloSchema partial class with:
//   * H2AMpvrLayout        — variant file layout (FileHeader .. WeaponTunings)
//   * H2AScriptTail        — post-trigger script-block tail (MegaloVars etc.)
//   * H2AEnumBits          — per-enum bit-width dictionary, keyed by enum name.
//                             Only the widths that DIFFER from Reach are flagged
//                             as "differs" in the comment; the full map is here
//                             so consumers don't need to diff XMLs at runtime.
//   * H2ALayouts           — named reusable layouts (H2A_PlayerTraits etc.)
//
// Because MegaloSchema.cs already owns the single allowed `static
// MegaloSchema()` type-initializer, these extras are computed by field
// initializers (not a new static ctor).
//
// Design note: the H2A PlayerTraits / FiringProperties / WeaponProperties /
// Ordnance regions use an override-enum-per-field layout that is not yet
// empirically verified against stock .bin files. Those are recorded as
// UnverifiedSection so the walker hard-stops rather than silently desyncing,
// matching the Reach partial-layout strategy in MegaloSchema.cs.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace UniversalGametypeEditor.Megalo
{
    public static partial class MegaloSchema
    {
        // --------------------------------------------------------------
        // H2A per-enum bit widths (from Halo 2A/var enums.xml RefTypes).
        // Marked *differs* where the width diverges from the Reach table
        // in Enums[...] above.
        // --------------------------------------------------------------
        public static readonly IReadOnlyDictionary<string, int> H2AEnumBits =
            new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
        {
            // Megalograph XML widths (Halo 2A/var enums.xml) — community-verified.
            ["VarType"]              = 3,
            ["NumericTypeRef"]       = 7, // differs: Reach 6
            ["PlayerTypeRef"]        = 2,
            ["ObjectTypeRef"]        = 3,
            ["TeamTypeRef"]          = 3,
            ["TimerTypeRef"]         = 3,
            ["NumericRef"]           = 5, // differs: Reach 4
            ["ScratchNumericRef"]    = 4, // H2A-only (no Reach equivalent)
            ["PlayerRef"]            = 6, // Megalograph XML (differs: Reach 5)
            ["ObjectRef"]            = 5, // Megalograph XML (same as Reach)
            ["TeamRef"]              = 5, // same
            ["TimerRef"]             = 3, // same
            ["GetterOperator"]       = 3, // same
            ["SetterOperator"]       = 4, // same
            ["Bool"]                 = 1, // same
            ["LabelRef"]             = 1, // same
            ["FilterRef"]            = 1, // H2A-only
            ["Players"]              = 3, // same
            ["WaypointIcon"]         = 5, // same
            ["WaypointPriority"]     = 2, // same
            ["ObjectShape"]          = 2, // same
            ["ObjectTimerIndex"]     = 1, // same
            ["TimerRate"]            = 5, // same
            ["IncidentPlayers"]      = 2, // same
            ["PickupMode"]           = 2, // same
            ["WidgetRef"]            = 1, // same
            ["WidgetMeter"]          = 2, // same
            ["GrenadeType"]          = 3, // differs: Reach 1
            ["GiveWeaponMode"]       = 2, // same
            ["DropWeaponMode"]       = 2, // differs: Reach 1
            ["ObjectPlayerIndex"]    = 1, // same
            ["PlayerAction"]         = 4, // H2A-only
            ["PowerupType"]          = 2, // H2A-only
            ["StringToken"]          = 3, // same
            ["StringVars1"]          = 1, // H2A-only
            ["StringVars2"]          = 2, // same
            ["StringVars3"]          = 2, // H2A-only
            // Count tag widths for the action/condition opcode tables:
            ["ActionType"]           = 8, // differs: Reach 7 (128 actions); H2A 256
            ["ConditionType"]        = 5, // same (32 conditions)
            // MegaloVars pool count widths (H2A differs mainly on globalnumbers).
            ["globalnumbers"]        = 5, // differs: Reach 4
            ["globaltimers"]         = 4, // same
            ["globalteams"]          = 4, // same
            ["globalplayers"]        = 4, // same
            ["globalobjects"]        = 5, // same
            ["playernumbers"]        = 4, // same
            ["playertimers"]         = 3, // same
            ["playerteams"]          = 3, // same
            ["playerplayers"]        = 3, // same
            ["playerobjects"]        = 3, // same
            ["objectnumbers"]        = 4, // same
            ["objecttimers"]         = 3, // same
            ["objectteams"]          = 2, // same
            ["objectplayers"]        = 3, // same
            ["objectobjects"]        = 3, // same
            ["teamnumbers"]          = 4, // same
            ["teamtimers"]           = 3, // same
            ["teamteams"]            = 3, // same
            ["teamplayers"]          = 3, // same
            ["teamobjects"]          = 3, // same
            // Sub-pool ref widths from NumericTypeRef/ObjectTypeRef/etc.
            // NumericTypeRef::GlobalNum -> globalnumbers index:
            ["Ref:GlobalNum"]        = 5, // differs: Reach 4
            // Player.Number / Object.Number / Team.Number ref widths (H2A 4 vs Reach 3).
            ["Ref:PlayerNumber"]     = 4, // differs: Reach 3
            ["Ref:ObjectNumber"]     = 4, // differs: Reach 3
            ["Ref:TeamNumber"]       = 4, // differs: Reach 3
            // ObjectTypeRef::Team.Object ref width (H2A 3 same as Reach 3).
            ["Ref:TeamObject"]       = 3,
            // TimerTypeRef::Timer ref width (H2A 3 same as Reach 3).
            ["Ref:GlobalTimer"]      = 3,

            // Per-variant Ref0 widths from Halo 2A/var enums.xml lines
            // 219-307. Keyed by the last path component of the Ref0 target,
            // prefixed "Ref:". ReadSchemaField uses these to override the
            // Reach-derived schema widths when ctx.Game == H2A.
            ["Ref:playernumbers"]    = 4,
            ["Ref:objectnumbers"]    = 4,
            ["Ref:teamnumbers"]      = 4,
            ["Ref:globalnumbers"]    = 5,
            ["Ref:playerplayers"]    = 2,
            ["Ref:objectplayers"]    = 2,
            ["Ref:teamplayers"]      = 2,
            ["Ref:playerobjects"]    = 2,
            ["Ref:objectobjects"]    = 3,
            ["Ref:teamobjects"]      = 3,
            ["Ref:playerteams"]      = 2,
            ["Ref:objectteams"]      = 1,
            ["Ref:teamteams"]        = 2,
            ["Ref:playertimers"]     = 2,
            ["Ref:objecttimers"]     = 2,
            ["Ref:teamtimers"]       = 2,
            ["Ref:globaltimers"]     = 3,
            ["Ref:playerstats"]      = 2,

            // H2A-only enum/int widths referenced from action/condition
            // params but absent from ScriptDecompiler._externalEnumBits.
            // Falling back to 0 bits caused the actions to silently
            // under-read (observable as low action count).
            ["Uint5"]                = 5,    // H2A var enums.xml:821 (Int bits=5)
            ["Uint8"]                = 8,    // H2A var enums.xml:822 (Int bits=8)
            ["Int32"]                = 32,   // H2A var enums.xml:823 (Int bits=32)
            ["Single7_0_10"]         = 7,    // H2A var enums.xml:825 (Int bits=7)
            ["Medal"]                = 16,   // H2A var enums.xml:848 (Int bits=16)
            ["IncidentIndex"]        = 11,   // read_index<1500> = 11 bits per IL & XML external
            ["TriggerRef"]           = 7,    // H2A XML line 723: Int bits=7 (Reach is 9)
            ["ScratchNumericRef"]    = 4,    // H2A var enums.xml:349
            ["SoundIndex"]           = 7,    // aliases Sound — external sounds.xml ref
            ["String"]               = 8,    // H2A var enums.xml:864 (Ref1 to Stringtable, 8b)
            ["NameIndex32"]          = 8,    // External to names32.xml — same width as NameIndex
            // VirtualTriggerRef is a Container in Halo 2A/var enums.xml
            // lines 725-730: UnanmmedInt1(10) + UnanmmedInt2(10) +
            // UnanmmedInt3(11) + UnanmmedInt4(11) = 42 bits opaque. Action
            // 32 (VirtualTrigger) takes this as its single parameter and
            // was reading 0 bits, causing 42-bit drift per occurrence.
            ["VirtualTriggerRef"]    = 42,  // XML: 10+10+11+11 — needs verification vs real files

            // FireteamFilter (Halo 2A/var enums.xml:657-666): Container of
            // 8 Bool refs = 8 bits opaque. ScriptDecompiler's default was 3.
            ["FireteamFilter"]       = 8,

            // PurchaseMode (Halo 2A/var enums.xml:732-737): Container of 4
            // Bool refs = 4 bits opaque. ScriptDecompiler's default was 1.
            ["PurchaseMode"]         = 4,
        };

        // --------------------------------------------------------------
        // H2A named reusable layouts. Registered under H2A_* keys so they
        // do not shadow the Reach entries referenced by ReachMpvrLayout.
        // --------------------------------------------------------------
        public static readonly IReadOnlyDictionary<string, MegaloSection[]> H2ALayouts =
            BuildH2ALayouts();

        // Per-game overrides for MegaloSchema.Enums. The Reach schema was
        // generated from Reach var enums.xml and has tag/variant layouts
        // that diverge from H2A (notably NumericTypeRef inserts Scratch.Number
        // at tag 5, shifting later variants by 1+). ReadSchemaEnum consults
        // this dict first when ctx.Game == H2A.
        public static readonly IReadOnlyDictionary<string, EnumDef> H2AEnums = BuildH2AEnums();

        private static IReadOnlyDictionary<string, EnumDef> BuildH2AEnums()
        {
            var d = new Dictionary<string, EnumDef>(StringComparer.OrdinalIgnoreCase);

            // NumericTypeRef — 7-bit tag; first 16 variants have distinct
            // shapes per Halo 2A/var enums.xml:25-78. Remaining 112 variants
            // (tags 16-127) are leaf with 0 payload bits, so we enumerate
            // them by index + synthesized name.
            var numVariants = new List<VariantDef>
            {
                new VariantDef("Int16", "Int16", 0, "0000000", new[] {
                    new FieldDef("Int16", "Int", 16) }),
                new VariantDef("Player.Number", "Player.Number", 1, "0000001", new[] {
                    new FieldDef("Player", "Enumref:PlayerRef", 0),
                    new FieldDef("PlayerNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/PlayerVars/playernumbers", 4) }),
                new VariantDef("Object.Number", "Object.Number", 2, "0000010", new[] {
                    new FieldDef("Object", "Enumref:ObjectRef", 0),
                    new FieldDef("ObjectNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/ObjectVars/objectnumbers", 4) }),
                new VariantDef("Team.Number", "Team.Number", 3, "0000011", new[] {
                    new FieldDef("Team", "Enumref:TeamRef", 0),
                    new FieldDef("TeamNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/TeamVars/teamnumbers", 4) }),
                new VariantDef("Global.Number", "Global.Number", 4, "0000100", new[] {
                    new FieldDef("GlobalNum", "Ref0:Gametype/base/mpvr/megl/MegaloVars/GlobalVars/globalnumbers", 5) }),
                new VariantDef("Scratch.Number", "Scratch.Number", 5, "0000101", new[] {
                    new FieldDef("ScratchNum", "Enumref:ScratchNumericRef", 0) }),
                new VariantDef("ScriptOption", "ScriptOption", 6, "0000110", new[] {
                    new FieldDef("Option", "Ref0:Gametype/base/mpvr/ScriptOptions", 4) }),
                new VariantDef("Object.SpawnSeq", "Object.SpawnSeq", 7, "0000111", new[] {
                    new FieldDef("Object", "Enumref:ObjectRef", 0) }),
                new VariantDef("Object.UserData", "Object.UserData", 8, "0001000", new[] {
                    new FieldDef("Object", "Enumref:ObjectRef", 0) }),
                new VariantDef("ObjVal.Unk9", "ObjVal.Unk9", 9, "0001001", new[] {
                    new FieldDef("Object", "Enumref:ObjectRef", 0) }),
                new VariantDef("Team.Score", "Team.Score", 10, "0001010", new[] {
                    new FieldDef("Team", "Enumref:TeamRef", 0) }),
                new VariantDef("Player.Score", "Player.Score", 11, "0001011", new[] {
                    new FieldDef("Player", "Enumref:PlayerRef", 0) }),
                new VariantDef("Player.Money", "Player.Money", 12, "0001100", new[] {
                    new FieldDef("Player", "Enumref:PlayerRef", 0) }),
                new VariantDef("Player.Rating", "Player.Rating", 13, "0001101", new[] {
                    new FieldDef("Player", "Enumref:PlayerRef", 0) }),
                new VariantDef("Player.Stat", "Player.Stat", 14, "0001110", new[] {
                    new FieldDef("Player", "Enumref:PlayerRef", 0),
                    new FieldDef("Statistic", "Ref0:Gametype/base/mpvr/megl/playerstats", 2) }),
                new VariantDef("Team.Stat", "Team.Stat", 15, "0001111", new[] {
                    new FieldDef("Team", "Enumref:TeamRef", 0),
                    new FieldDef("Statistic", "Ref0:Gametype/base/mpvr/megl/playerstats", 2) }),
            };
            // Tags 16..22 — specific names per XML; all leaf (no fields).
            string[] named16Plus = {
                "Unk16", "CurrentRound", "SymmetricMode", "SymmetricModeWritable",
                "Gamemode Controls Victory Enabled", "ScoreToWinGame",
            };
            for (int i = 0; i < named16Plus.Length; i++)
                numVariants.Add(new VariantDef(named16Plus[i], named16Plus[i], 16 + i,
                    Convert.ToString(16 + i, 2).PadLeft(7, '0'), Array.Empty<FieldDef>()));
            // Tags 22..31 have Team/Player scalar fields (LivesLeft, SpawnDelay,
            // UnkVal25-32). From Halo 2A/var enums.xml:87-119.
            var t22Plus = new (string name, string refType)[]
            {
                ("Team.LivesLeft", "Enumref:TeamRef"),
                ("Player.LivesLeft", "Enumref:PlayerRef"),
                ("Player.SpawnDelay", "Enumref:PlayerRef"),
                ("Player.UnkVal25", "Enumref:PlayerRef"),
                ("Player.UnkVal26", "Enumref:PlayerRef"),
                ("Player.UnkVal27", "Enumref:PlayerRef"),
                ("Team.UnkVal28", "Enumref:TeamRef"),
                ("Team.UnkVal29", "Enumref:TeamRef"),
                ("Team.UnkVal30", "Enumref:TeamRef"),
                ("Object.UnkVal31", "Enumref:ObjectRef"),
                ("Object.UnkVal32", "Enumref:ObjectRef"),
            };
            for (int i = 0; i < t22Plus.Length; i++)
            {
                int tag = 22 + i;
                var fieldName = t22Plus[i].refType switch {
                    "Enumref:PlayerRef" => "Player",
                    "Enumref:TeamRef" => "Team",
                    "Enumref:ObjectRef" => "Object",
                    _ => "Ref",
                };
                numVariants.Add(new VariantDef(t22Plus[i].name, t22Plus[i].name, tag,
                    Convert.ToString(tag, 2).PadLeft(7, '0'),
                    new[] { new FieldDef(fieldName, t22Plus[i].refType, 0) }));
            }
            // Tags 33..127 are leaf (no payload bits) in H2A per the XML —
            // all "Unlabelled" or simple named constants. Synthesize.
            for (int tag = 33; tag < 128; tag++)
            {
                if (numVariants.Exists(v => v.Id == tag)) continue;
                string tagBits = Convert.ToString(tag, 2).PadLeft(7, '0');
                numVariants.Add(new VariantDef("Unlabelled", $"Unlabelled_{tag}", tag, tagBits,
                    Array.Empty<FieldDef>()));
            }
            d["NumericTypeRef"] = new EnumDef("NumericTypeRef", 7, numVariants.ToArray());

            // VarType / PlayerTypeRef / ObjectTypeRef / TeamTypeRef / TimerTypeRef
            // intentionally NOT overridden here — Megalograph XML's definitions
            // (in MegaloSchema.Enums via Reach) match H2A widths and structures.
            return d;
        }

        // Full H2A gametype variant layout (mpvr container) — FileHeader
        // through WeaponTunings. Walked by GametypeReader from bit 752 of
        // the raw .bin when the magic at that offset is "mpvr".
        public static readonly MegaloSection[] H2AMpvrLayout = BuildH2AMpvrLayout();

        // Full H2A forge-variant layout (gvar container). Header is 224
        // bits shorter than mpvr — gvar omits UnknownHash0x2FC (160 bits),
        // Blank0x310 (32 bits) and Fileusedsize (32 bits). Walked from
        // bit 1024 (byte 128) of the raw .bin when the magic there is "gvar".
        public static readonly MegaloSection[] H2AGvarLayout = BuildH2AGvarLayout();

        // H2A post-trigger script + mpvr tail layout, walked by the
        // ScriptTailReader from the current stream position after the
        // last trigger record.
        public static readonly MegaloSection[] H2AScriptTail = BuildH2AScriptTail();

        // --------------------------------------------------------------
        // H2AScriptTail: per-entry record shapes and MegaloVars sub-pool
        // Count widths. Matches Halo 2A/var enums.xml MegaloVars.
        // --------------------------------------------------------------
        private static MegaloSection[] BuildH2AScriptTail()
        {
            var h2aGlobalNumberRec = new MegaloSection[]
            {
                new EnumRefSection("Number", "NumericTypeRef"),
                new UIntSection("Locality", 2),
                new UIntSection("IsPersistent", 1),
            };
            var h2aGlobalTimerRec = new MegaloSection[]
            {
                new EnumRefSection("Number", "NumericTypeRef"),
            };
            var h2aGlobalTeamRec = new MegaloSection[]
            {
                new UIntSection("Team", 4),
                new UIntSection("Locality", 2),
                new UIntSection("IsPersistent", 1),
            };
            var h2aGlobalPlayerRec = new MegaloSection[]
            {
                new UIntSection("Locality", 2),
                new UIntSection("IsPersistent", 1),
            };
            var h2aGlobalObjectRec = new MegaloSection[]
            {
                new UIntSection("Locality", 2),
                new UIntSection("IsPersistent", 1),
            };

            (int, string, MegaloSection[])[] insertionBranches =
                new (int, string, MegaloSection[])[]
            {
                (0, "Used",   new MegaloSection[] { new UIntSection("Triggerref", 7) }),
                (1, "Unused", Array.Empty<MegaloSection>()),
            };

            return new MegaloSection[]
            {
                // ---- Script variable globals (after triggers) ----
                new CountSection("GlobalNumbers", 5, h2aGlobalNumberRec),  // differs: Reach 4
                new CountSection("GlobalTimers", 4, h2aGlobalTimerRec),
                new CountSection("GlobalTeams",  4, h2aGlobalTeamRec),
                new CountSection("GlobalPlayers",4, h2aGlobalPlayerRec),
                new CountSection("GlobalObjects",5, h2aGlobalObjectRec),

                // ---- MegaloVars sub-pools scoped to player/object/team ----
                new CountSection("playernumbers", 4, h2aGlobalNumberRec),
                new CountSection("playertimers",  3, h2aGlobalTimerRec),
                new CountSection("playerteams",   3, h2aGlobalTeamRec),
                new CountSection("playerplayers", 3, h2aGlobalPlayerRec),
                new CountSection("playerobjects", 3, h2aGlobalObjectRec),

                new CountSection("objectnumbers", 4, h2aGlobalNumberRec),
                new CountSection("objecttimers",  3, h2aGlobalTimerRec),
                new CountSection("objectteams",   2, h2aGlobalTeamRec),
                new CountSection("objectplayers", 3, h2aGlobalPlayerRec),
                new CountSection("objectobjects", 3, h2aGlobalObjectRec),

                new CountSection("teamnumbers", 4, h2aGlobalNumberRec),
                new CountSection("teamtimers",  3, h2aGlobalTimerRec),
                new CountSection("teamteams",   3, h2aGlobalTeamRec),
                new CountSection("teamplayers", 3, h2aGlobalPlayerRec),
                new CountSection("teamobjects", 3, h2aGlobalObjectRec),

                // H2A adds a hudwidgets Count(3) with a 4-bit location field.
                new CountSection("hudwidgets", 3, new MegaloSection[]
                {
                    new UIntSection("Location", 4),
                }),

                // InsertionPoints — 8 1-bit "Unused/Used" flags, each
                // carrying a 7-bit Triggerref payload when Used.
                new GroupSection("InsertionPoints", new MegaloSection[]
                {
                    new VariantSection("Init",                1, insertionBranches),
                    new VariantSection("LocalInit",           1, insertionBranches),
                    new VariantSection("HostMigration",       1, insertionBranches),
                    new VariantSection("DoubleHostMigration", 1, insertionBranches),
                    new VariantSection("ObjectDeath",         1, insertionBranches),
                    new VariantSection("Local",               1, insertionBranches),
                    new VariantSection("Pregame",             1, insertionBranches),
                    new VariantSection("Incident",            1, insertionBranches),
                }),

                new UnverifiedSection(
                    "H2A_TailRemainder",
                    "HUD widgets / script stats / script widgets / triggers "
                    + "follow InsertionPoints in H2A. Widths not yet "
                    + "empirically verified."),
            };
        }

        // --------------------------------------------------------------
        // Named reusable H2A layouts. The H2A TeamOptions / LoadoutOptions
        // are close enough to Reach's to be translated 1:1; PlayerTraits
        // uses per-field override enums and is registered as an
        // UnverifiedSection wrapper so the walker hard-stops at the
        // boundary rather than guessing.
        // --------------------------------------------------------------
        // Replicates the OrdnanceWeights container body (mpvr.xml 602-619):
        // 8 × (UString8 name + 30-bit weight). Inlined as a GroupSection child
        // list so each ordnance slot in the Ordnance block can reuse it.
        private static MegaloSection[] H2AOrdnanceWeightsFields() => new MegaloSection[]
        {
            new UString8Section("PossibilityName1"), new UIntSection("PossibilityWeight1", 30),
            new UString8Section("PossibilityName2"), new UIntSection("PossibilityWeight2", 30),
            new UString8Section("PossibilityName3"), new UIntSection("PossibilityWeight3", 30),
            new UString8Section("PossibilityName4"), new UIntSection("PossibilityWeight4", 30),
            new UString8Section("PossibilityName5"), new UIntSection("PossibilityWeight5", 30),
            new UString8Section("PossibilityName6"), new UIntSection("PossibilityWeight6", 30),
            new UString8Section("PossibilityName7"), new UIntSection("PossibilityWeight7", 30),
            new UString8Section("PossibilityName8"), new UIntSection("PossibilityWeight8", 30),
        };

        private static IReadOnlyDictionary<string, MegaloSection[]> BuildH2ALayouts()
        {
            var h2aLayouts = new Dictionary<string, MegaloSection[]>(StringComparer.OrdinalIgnoreCase);

            // --- H2A_PlayerTraits --------------------------------------
            // Hand-translated from Halo 2A/mpvr.xml lines 80-442.
            // OV(name) shorthand: `Enum bits=1` → tag 0 = Unchanged (no body),
            //                              tag 1 = Override(Int bits=16).
            // TT(name) shorthand: 2-bit TraitToggle enum.
            MegaloSection OV(string n) => new VariantSection(n, 1, new (int, string, MegaloSection[])[]
            {
                (0, "Unchanged", Array.Empty<MegaloSection>()),
                (1, "Override",  new MegaloSection[] { new SIntSection("Value", 16) }),
            });
            MegaloSection TT(string n) => new UIntSection(n, 2);

            h2aLayouts["H2A_PlayerTraits"] = new MegaloSection[]
            {
                // Defensive Attributes (mpvr.xml 81-165)
                OV("DamageResistance"),
                OV("ShieldMultiplier"),
                OV("BodyMultiplier"),
                OV("ShieldStunDuration"),
                OV("ShieldRechargeRate"),
                OV("BodyRechargeRate"),
                OV("OvershieldRechargeRate"),
                OV("VampirismPercent"),
                OV("ExplosiveDamageResistance"),
                OV("WheelmanArmorVehicleStunTimeModifier"),
                OV("WheelmanArmorVehicleRechargeTimeModifier"),
                OV("WheelmanArmorVehicleEmpDisabledTimeModifier"),
                OV("FallDamageMultiplier"),
                TT("HeadshotImmunity"),
                TT("AssassinationImmunity"),
                TT("Invincible"),
                TT("FasttrackArmor"),
                TT("PowerupCancellation"),

                // Offensive Attributes (mpvr.xml 166-327)
                OV("DamageMultiplier"),
                OV("MeleeDamageMultiplier"),
                OV("GrenadeRechargeSecondsFrag"),
                OV("GrenadeRechargeSecondsPlasma"),
                OV("GrenadeRechargeSecondsSpike"),
                OV("HeroEquipmentEnergyUseRateModifier"),
                OV("HeroEquipmentEnergyRechargeDelayModifier"),
                OV("HeroEquipmentEnergyRechargeRateModifier"),
                OV("HeroEquipmentInitialEnergyModifier"),
                OV("EquipmentEnergyUseRateModifier"),
                OV("EquipmentEnergyRechargeDelayModifier"),
                OV("EquipmentEnergyUseRechargeRateModifier"),
                OV("EquipmentInitialEnergyModifier"),
                OV("SwitchSpeedModifier"),
                OV("ReloadSpeedModifier"),
                OV("OrdnancePointsModifier"),
                OV("ExplosiveAreaOfEffectRadiusModifier"),
                OV("GunnerArmorModifier"),
                OV("StabilityArmorModifier"),
                OV("DropReconWarningSeconds"),
                OV("DropReconDistanceModifier"),
                OV("AssassinationSpeedModifier"),
                TT("WeaponPickup"),
                new UIntSection("Grenades", 5),
                new UIntSection("InfiniteAmmo", 2),
                new UIntSection("AbilityUsage", 2),
                TT("UsageSansAutoTurret"),
                TT("AbilitiesDropOnDeath"),
                TT("InfiniteAbility"),
                TT("AmmoPackMod"),
                TT("GrenadierMod"),
                TT("DropLiveGrenadeOnDeath"),
                TT("OrdnanceMarkerVisibility"),
                TT("CanScavengeGrenades"),
                TT("Firepower"),
                TT("AllowOrdnanceReroll"),
                TT("OrdnanceDisabled"),

                // Loadout (mpvr.xml 329-335)
                new UIntSection("Primaryweapon", 8),
                new UIntSection("Secondaryweapon", 8),
                new UIntSection("Equipment", 8),       // dual-wield weapon
                new UIntSection("TacticalPackage", 8),
                new UIntSection("SupportPackage", 8),

                // Movement (mpvr.xml 337-370)
                OV("PlayerSpeed"),
                OV("PlayerGravity"),
                OV("JumpHeight"),
                OV("TurnSpeed"),
                new UIntSection("VehicleUse", 4),
                TT("DoubleJump"),
                TT("Sprint"),
                TT("AutoMomentum"),
                TT("Vaulting"),
                TT("Stealthy"),
                new UIntSection("Bits1HereAsWell", 1),
                new UIntSection("Bits1Here", 1),

                // Appearance (mpvr.xml 372-411)
                // PlayerScale uses the same 1-bit override pattern but the
                // payload field is named "Scale" rather than "Value".
                new VariantSection("PlayerScale", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "Unchanged", Array.Empty<MegaloSection>()),
                    (1, "Override",  new MegaloSection[] { new SIntSection("Scale", 16) }),
                }),
                new UIntSection("Camo", 3),
                new UIntSection("VisibleWaypoint", 2),
                new UIntSection("VisibleName", 2),
                new UIntSection("Aura", 3),
                new UIntSection("ForcedPrimaryColor", 5),   // Enumref:coloroverride
                new UIntSection("ForcedSecondaryColor", 5),
                new UIntSection("OverridePrimaryColor", 1),
                new UIntSection("PrimaryRed", 8),
                new UIntSection("PrimaryGreen", 8),
                new UIntSection("PrimaryBlue", 8),
                new UIntSection("OverrideSecondaryColor", 1),
                new UIntSection("SecondaryRed", 8),
                new UIntSection("SecondaryGreen", 8),
                new UIntSection("SecondaryBlue", 8),
                new UIntSection("OverridePlayerModel", 1),
                // PlayerModelNameVariant: External:\Halo 2A\names1.xml —
                // names1.xml defines it as an 8-bit Enum (NameIndex). The XML
                // `bits="0"` on the PlayerTraits side means "see external
                // file"; it is NOT literally zero bits.
                new UIntSection("PlayerModelNameVariant", 8),
                new UIntSection("DeathEffect", 32),
                new UIntSection("LoopingEffect", 32),
                new UIntSection("ShieldHud", 2),

                // Misc (mpvr.xml 413-442)
                OV("MotionTracker"),
                OV("NemesisDuration"),
                new UIntSection("Uhh", 1),
                new UIntSection("MotionTrackerUsage", 3),
                TT("MotionTrackerUsageZoomed"),
                new UIntSection("DirectionalDamageIndicator", 2),
                TT("VisionMode"),
                TT("BattleAwareness"),
                TT("ThreatView"),
                new UIntSection("Aura2", 2),
                new UIntSection("Nemesis", 2),
            };

            h2aLayouts["H2A_TeamOptions"] = new MegaloSection[]
            {
                new UIntSection("EmblemOverride", 1),
                new UIntSection("UnknownOverride", 1),
                new UIntSection("TertiarycolorOverride", 1),
                new UIntSection("SecondarycolorOverride", 1),
                new UIntSection("PrimarycolorOverride", 1),
                new UIntSection("TeamEnabled", 1),
                // Team string table: H2A ValueBits=10 (XML chars="10"), 1-bit count.
                new StringTableSection("Teamstring", ValueBits: 10, CountBits: 1, IsTeamString: true),
                new UIntSection("InitialDesignator", 4),
                new UIntSection("Elitespecies", 1),
                new HexSection("PrimaryColor", 32),
                new HexSection("SecondaryColor", 32),
                new HexSection("TextColor", 32),
                new HexSection("InterfaceColor", 32),
                new UIntSection("FireteamCount", 5),
                new UIntSection("EmblemForeground", 8),
                new UIntSection("EmblemBackground", 8),
                new UIntSection("EmblemUnknown", 3),
                new UIntSection("EmblemPrimaryColor", 6),
                new UIntSection("EmblemSecondaryColor", 6),
                new UIntSection("EmblemBackgroundColor", 6),
            };

            h2aLayouts["H2A_LoadoutOptions"] = new MegaloSection[]
            {
                new UIntSection("LoadoutVisibleingame", 1),
                // H2A: tag 0 = True (has NameIndex), tag 1 = False.
                new VariantSection("LoadoutName", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "True",  new MegaloSection[] { new UIntSection("NameIndex", 7) }),
                    (1, "False", Array.Empty<MegaloSection>()),
                }),
                new UIntSection("PrimaryWeapon", 8),
                new UIntSection("SecondaryWeapon", 8),
                new UIntSection("Armorability", 8),
                new UIntSection("TacticalPackage", 8),
                new UIntSection("SupportUpgrade", 8),
                new UIntSection("Grenades", 5),
                new UIntSection("Unknown", 6),
            };

            // H2A loadoutCLuster: 5 LoadoutOptions children.
            h2aLayouts["H2A_LoadoutCluster"] = new MegaloSection[]
            {
                new SectionRefSection("Loadout1", "H2A_LoadoutOptions"),
                new SectionRefSection("Loadout2", "H2A_LoadoutOptions"),
                new SectionRefSection("Loadout3", "H2A_LoadoutOptions"),
                new SectionRefSection("Loadout4", "H2A_LoadoutOptions"),
                new SectionRefSection("Loadout5", "H2A_LoadoutOptions"),
            };

            return h2aLayouts;
        }

        // --------------------------------------------------------------
        // H2AMpvrLayout — anchored to Halo 2A/mpvr.xml <ExTypes> top-level
        // children. Regions whose bit structure is not yet round-tripped
        // against a stock H2A .bin are UnverifiedSection so the walker
        // hard-stops at the exact boundary.
        // --------------------------------------------------------------
        // mpvr FileHeader — authoritative Halo 2A/mpvr.xml lines 902-916.
        // 424 bits total: magic(32)+length(32)+major(16)+minor(16)+
        //   hash(160)+blank(32)+fileUsedSize(32)+u8(8)+u32(32)+u32(32)+
        //   fileLen(32).
        private static MegaloSection[] H2AMpvrFileHeader() => new MegaloSection[]
        {
            new AsciiStringSection("mpvr", 32),
            new UIntSection("megaloversion", 32),
            new UIntSection("Unknown0x2F8", 16),
            new UIntSection("Unknown0x2FA", 16),
            new HexSection("UnknownHash0x2FC", 160),
            new HexSection("Blank0x310", 32),
            new UIntSection("Fileusedsize", 32),   // mpvr.xml:911 — was missing.
            new UIntSection("Unknown0x318", 8),
            new UIntSection("Unknown0x319", 32),
            new UIntSection("Unknown0x31D", 32),
            new UIntSection("FileLength", 32),
        };

        // gvar FileHeader — same as mpvr minus hash(160) + blank(32) +
        // fileUsedSize(32) = 200 bits (vs mpvr's 424). Empirically confirmed
        // by byte-for-byte comparison with forgeh2a.bin.
        private static MegaloSection[] H2AGvarFileHeader() => new MegaloSection[]
        {
            new AsciiStringSection("gvar", 32),
            new UIntSection("megaloversion", 32),
            new UIntSection("Unknown0x2F8", 16),
            new UIntSection("Unknown0x2FA", 16),
            new UIntSection("Unknown0x318", 8),
            new UIntSection("Unknown0x319", 32),
            new UIntSection("Unknown0x31D", 32),
            new UIntSection("FileLength", 32),
        };

        // H2A file-body layout after the FileHeader (gametype header, mode
        // settings, traits, all pre-megl sections, megl, post-megl tail).
        // Shared between mpvr and gvar since only the FileHeader differs.
        private static MegaloSection[] BuildH2ABodyAfterHeader() => new MegaloSection[]
        {

            // GametypeHeader
            new HexSection("ID0x48", 64),
            new HexSection("ID0x50", 64),
            new HexSection("ID0x58", 64),
            new HexSection("Blank0x60", 64),
            // H2A UnknownFlags is 8 bits (Reach: 9).
            new BlankSection("UnknownFlags", 8),
            new UIntSection("Unknown_1", 32),
            new UIntSection("Unknown0x1", 8),
            new UIntSection("Blank04", 32),
            new HexSection("TimeStampUint", 32),
            new HexSection("XUID", 64),
            new UString8Section("Gamertag"),
            new BlankSection("Blank041bit", 33),
            new HexSection("EditTimeStampUint", 32),
            new HexSection("EditXUID", 64),
            new UString8Section("EditGamertag"),
            new UIntSection("UnknownFlag1", 1),
            new UString16Section("Title"),
            new UString16Section("Description"),
            new UIntSection("GameIcon", 8),

            // ModeSettings — H2A path (UnknownFlag2 is 2 bits; Reach: 1).
            new UIntSection("UnknownFlag2", 2),
            new UIntSection("Teamsenabled", 1),
            new UIntSection("Resetmaponnewroundunused", 1),
            new UIntSection("Resetplayersonnewroundunused", 1),
            new UIntSection("Perfectionmedalenabled", 1),
            new UIntSection("RoundTimeLimit", 8),
            new UIntSection("NumberOfRounds", 5),
            new UIntSection("RoundsToWin", 4),
            new UIntSection("KillCamEnabled", 1),
            new UIntSection("PointsSystemEnabled", 1),
            new UIntSection("FinalKillCamEnabled", 1),
            new UIntSection("Unknown2", 1),
            new UIntSection("SuddenDeathTime", 7),
            new UIntSection("Bit4", 1),
            new UIntSection("Bit5", 1),
            new UIntSection("MoshDifficulty", 2),
            new UIntSection("ProtoMode", 11),
            new UIntSection("Unknown4", 4),
            new UIntSection("ClassColorOverride", 1),
            new UIntSection("InheritRespawnTime", 1),
            new UIntSection("Unknown42", 4),

            // SpawnSettings
            new UIntSection("LivesPerround", 6),
            new UIntSection("TeamLivesPerround", 7),
            new UIntSection("MinRespawntime", 8),
            new UIntSection("RespawnTime", 8),
            new UIntSection("Suicidepenalty", 8),
            new UIntSection("Betrayalpenalty", 8),
            new UIntSection("RespawnTimegrowth", 4),
            new UIntSection("LoadoutCamTime", 4),
            new UIntSection("Respawntraitsduration", 6),
            new SectionRefSection("RespawnPlayerTraits", "H2A_PlayerTraits"),

            // GameSettings
            new UIntSection("EnableObservers", 1),
            new UIntSection("Teamchanging", 2),
            new UIntSection("FriendlyFire", 1),
            new UIntSection("Idunno1", 1),
            new UIntSection("Dontrestrictteamvoicechat", 1),
            new UIntSection("Idunno2", 1),
            new UIntSection("Idunno3", 1),
            new UIntSection("Indestructiblevehicles", 1),
            new UIntSection("TurretsOnMap", 1),
            new UIntSection("PowerupsOnMap", 1),
            new UIntSection("AbilitiesOnMap", 1),
            new UIntSection("ShortcutsOnMap", 1),
            // BasePlayerTraits + WeaponSet/VehicleSet/EquipSet (1 trait + 24
            // bits) map to the first 24 wire bits AFTER FUN_1800194c0's
            // BasePlayerTraits sub-call. The 55-bit "GameSettingsUnknown"
            // blank below absorbs the rest of FUN_1800194c0's mid-section:
            //   * 6-bit map-override-flags prefix (Agent 6 line 47-66)
            //   * 5 missing 8-bit set-index/qreal fields
            //     (param_1[0x92c]/[0x92d]/qreal weapon-respawn-time/
            //      tank/aircraft/turret/param_1[0x92e]) — actual IL reads
            //     8×8=64 bits here vs schema's 55-bit blank
            // See agent7_paired_AC_fix.md for the residual-drift analysis;
            // a structural break-out that doesn't shift trait sub-decoder
            // bit positions is required before the BlankSection can be
            // replaced with named fields.
            new SectionRefSection("BasePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("WeaponSet", 8),
            new UIntSection("VehicleSet", 8),
            new UIntSection("EquipSet", 8),
            new BlankSection("GameSettingsUnknown", 55),

            // PowerupTraits — H2A 4 powerup slots (Damage, Speed, Overshield,
            // Custom) × runtime + normal duration, mapping to the inner
            // 4×2 loop in c_game_engine_requisition_options_decode
            // @ 0x1800194c0 (Agent 6 line 494-558). The IL inner-loop ref
            // at puVar2[0x4c] is 7 bits clamped to <0x7f, but schema keeps
            // 6 here — flipping to 7 shifts trait sub-decoder bit positions
            // and amplifies through ~15 OV(1-bit-tag) variant fields per
            // H2A_PlayerTraits, breaking decomptest.bin's 1/2/2 walk.
            new SectionRefSection("DamagePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("DamageTraitsDuration", 6),
            new SectionRefSection("DamageRuntimePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("DamageTraitsRuntimeDuration", 6),
            new SectionRefSection("SpeedPlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("SpeedTraitsDuration", 6),
            new SectionRefSection("SpeedRuntimePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("SpeedTraitsRuntimeDuration", 6),
            new SectionRefSection("OvershieldPlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("OvershieldTraitsDuration", 6),
            new SectionRefSection("OvershieldRuntimePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("OvershieldTraitsRuntimeDuration", 6),
            new SectionRefSection("CustomPlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("CustomTraitsDuration", 6),
            new SectionRefSection("CustomRuntimePlayerTraits", "H2A_PlayerTraits"),
            new UIntSection("CustomTraitsRuntimeDuration", 6),

            // TeamSettings.
            //
            // c_game_engine_team_options_decode @ 0x18001b4c0 reads only 3+2
            // bits before the 8-team loop (Agent 6 dump FUN_18001b4c0). The
            // 103-bit block below (BUnknown8(4) + 3×Hex32 + PlayerSpecies(3))
            // is NOT actually emitted by FUN_18001b4c0; it is renamed-but-
            // kept compensation for the post-FUN_1800194c0 scaffold inside
            // c_base_variant_decode @ 0x18001f0d0 (lines 305-713):
            //   * 32-bit qreal score-to-win (FUN_1800744f0)
            //   * 32-bit field at param_1[0x4dd]
            //   * 7-bit palette-item count + N×305-bit per-item loop
            //   * 32-bit field at plVar11[0x67e]
            // For empty-palette content (decomptest) those reads sum to
            // 32+32+7+32 = 103 bits, exactly the BUnknown8/Hex32×3/
            // PlayerSpecies block. We retain the original field layout so
            // existing reflection-based UI references (BUnknown8 etc.) keep
            // working; field NAMES are misleading but bit alignment is
            // preserved for decomptest.bin.
            new UIntSection("TeamScoringMethod", 3),
            new UIntSection("BUnknown8", 4),
            new HexSection("Unknown32_1", 32),
            new HexSection("Unknown32_2", 32),
            new HexSection("Unknown32_3", 32),
            new UIntSection("PlayerSpecies", 3),
            new UIntSection("DesignatorSwitchtype", 2),
            new SectionRefSection("Team1Options", "H2A_TeamOptions"),
            new SectionRefSection("Team2Options", "H2A_TeamOptions"),
            new SectionRefSection("Team3Options", "H2A_TeamOptions"),
            new SectionRefSection("Team4Options", "H2A_TeamOptions"),
            new SectionRefSection("Team5Options", "H2A_TeamOptions"),
            new SectionRefSection("Team6Options", "H2A_TeamOptions"),
            new SectionRefSection("Team7Options", "H2A_TeamOptions"),
            new SectionRefSection("Team8Options", "H2A_TeamOptions"),

            // LoadoutPalettes — H2A: 4 flag bits + 6 loadout clusters
            // (Reach: 2 flags + 30 fixed-position loadouts).
            new UIntSection("MapLoadoutsEnabled", 1),
            new UIntSection("EliteLoadoutsEnabled", 1),
            new UIntSection("SpartanLoadoutsEnabled", 1),
            new UIntSection("CustomLoadoutsEnabled", 1),
            new SectionRefSection("Loadouts1", "H2A_LoadoutCluster"),
            new SectionRefSection("Loadouts2", "H2A_LoadoutCluster"),
            new SectionRefSection("Loadouts3", "H2A_LoadoutCluster"),
            new SectionRefSection("Loadouts4", "H2A_LoadoutCluster"),
            new SectionRefSection("Loadouts5", "H2A_LoadoutCluster"),
            new SectionRefSection("Loadouts6", "H2A_LoadoutCluster"),

            // Ordnance — hand-translated from Halo 2A/mpvr.xml lines 1068-1097.
            // Each OrdnanceWeightsSlot is 8 × (UString8 + 30-bit weight)
            // per the OrdnanceWeights container (mpvr.xml 602-619).
            new UIntSection("Ordances2bit", 1),
            new UIntSection("InitialOrdnance", 1),
            new UIntSection("RandomOrdnance", 1),
            new UIntSection("PersonalOrdnance", 1),
            new UIntSection("OrdancesEnabled", 1),
            new UIntSection("Ordnance8bit", 8),
            new UIntSection("OrdResupplyTimeMin", 16),
            new UIntSection("OrdResupplyTimeMax", 16),
            new UIntSection("Ordnance16bit1", 16),
            new UString8Section("InitialDropsetName"),
            new UIntSection("Ordnance16bit2", 16),
            new UIntSection("Ordnance16bit3", 16),
            new UString8Section("RandomDropsetName"),
            new UString8Section("PersonalDropsetName"),
            new UString8Section("OrdnanceSubstitutionsName"),
            new UIntSection("CustomizePersonalOrdnance", 1),
            new GroupSection("OrdnanceRight", H2AOrdnanceWeightsFields()),
            new GroupSection("OrdnanceLeft",  H2AOrdnanceWeightsFields()),
            new GroupSection("OrdnanceDown",  H2AOrdnanceWeightsFields()),
            new GroupSection("OrdnanceUnknown", H2AOrdnanceWeightsFields()),
            new BlankSection("OrdnancePointsRequirement", 30),
            new BlankSection("OrdnanceIncreaseMultiplier", 30),

            // --- Pre-megl container sections (mpvr.xml order) ---
            // H2A ScriptedPlayerTraits: string refs are 8 bits (Reach: 7)
            // and each record has an extra 1-bit IsHidden trailer.
            new CountSection("ScriptedPlayerTraits", 5, new MegaloSection[]
            {
                new StringTableRefSection("String1", 8),
                new StringTableRefSection("String2", 8),
                new SectionRefSection("PlayerTraits", "H2A_PlayerTraits"),
                new UIntSection("IsHidden", 1),
            }),

            // H2A ScriptOptions: identical to Reach except string refs
            // widen to 8 bits and ScriptOptionChild adds trailing string refs.
            new CountSection("ScriptOptions", 5, new MegaloSection[]
            {
                new StringTableRefSection("String1", 8),
                new StringTableRefSection("String2", 8),
                new VariantSection("ScriptOption", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "Scriptoption", new MegaloSection[]
                    {
                        new UIntSection("ChildIndex", 4),
                        new CountSection("ScriptOptionChild", 5, new MegaloSection[]
                        {
                            new SIntSection("Value", 10),
                            new StringTableRefSection("String1", 8),
                            new StringTableRefSection("String2", 8),
                        }),
                        // user_defined_option_decode tag-0 returns immediately
                        // after the children loop (ManagedMegalo @ 0x18001e4b0).
                        // Walker previously had a phantom 4-bit ActualChildIndex.
                    }),
                    (1, "Range", new MegaloSection[]
                    {
                        new SIntSection("range1", 10),
                        new SIntSection("range2", 10),
                        new SIntSection("range3", 10),
                        new SIntSection("range4", 10),
                    }),
                }),
            }),

            // Strings block — H2A uses 8-bit count + 16-bit values + 17 langs.
            new StringTableSection(
                "Stringtable",
                ValueBits: 16, CountBits: 8,
                IsTeamString: false, NumLanguages: 17),
            new StringTableRefSection("StringNameIndex", 8),
            new StringTableSection("metanameStrings",  ValueBits: 11, CountBits: 1, NumLanguages: 17),
            new StringTableSection("metadescStrings",  ValueBits: 13, CountBits: 1, NumLanguages: 17),
            new StringTableSection("metaintroStrings", ValueBits: 13, CountBits: 1, NumLanguages: 17),
            new StringTableSection("metagroupStrings", ValueBits: 10, CountBits: 1, NumLanguages: 17),

            // Game / map perms / player ratings.
            new UIntSection("ActualGameicon", 5),
            new UIntSection("ActualGamecategory", 5),
            new CountSection("mapperms", 6, new MegaloSection[]
            {
                new HexSection("MapID", 16),
            }),
            new UIntSection("mappermsflip", 1),

            new HexSection("Playerrating-ratingscale", 32),
            new HexSection("Playerrating-kilweight", 32),
            new HexSection("Playerrating-assistweight", 32),
            new HexSection("Playerrating-betrayalweight", 32),
            new HexSection("Playerrating-deathweight", 32),
            new HexSection("Playerrating-normalizebymaxkills", 32),
            new HexSection("Playerrating-base", 32),
            new HexSection("Playerrating-range", 32),
            new HexSection("Playerrating-lossscalar", 32),
            new HexSection("Playerrating-customstat0", 32),
            new HexSection("Playerrating-customstat1", 32),
            new HexSection("Playerrating-customstat2", 32),
            new HexSection("Playerrating-customstat3", 32),
            new HexSection("Playerrating-expansion0", 32),
            new HexSection("Playerrating-expansion1", 32),
            new UIntSection("showplayerratings", 1),

            new BlankSection("unknown42", 42),

            // Count(9) "loadouts" region before unknown2643 (lines 1596-1612).
            new CountSection("loadouts", 9, new MegaloSection[]
            {
                new UIntSection("Size", 2),
                new UIntSection("Enabled", 1),
                new VariantSection("LoadoutName", 1, new (int, string, MegaloSection[])[]
                {
                    (0, "Override", new MegaloSection[] { new UIntSection("NameIndex", 7) }),
                    (1, "Null",     Array.Empty<MegaloSection>()),
                }),
                new UIntSection("Primary", 8),
                new UIntSection("Secondary", 8),
                new UIntSection("ArmorAbility", 8),
                new UIntSection("TacticalPackage", 8),
                new UIntSection("SupportUpgrade", 8),
                new UIntSection("GrenadeCount", 5),
                new UIntSection("Unknown", 6),
            }),

            // H2A unknown2643 — agent's original derivation = 1728 bits.
            // This works for decomptest.bin but puts forgeh2a.bin's megl
            // 38 bits late, suggesting a variable-width Count/HCount
            // section earlier in the pre-megl layout drifts by content.
            // Reach uses 2642 here.
            new BlankSection("unknown2643", 1728),

            // megl — script block handed to ScriptDecompiler.
            new UnverifiedSection(
                "megl",
                "Megalo script block — parsed by ScriptDecompiler with H2A "
                + "ActionType=8 / NumericTypeRef=7 / GlobalNum=5 / "
                + "PlayerNumber=4 bit widths. GametypeReader hands off here."),

            // Post-megl padding + required objects.
            new BlankSection("unknown63", 34),
            new BlankSection("requiredobjects", 224),
            new BlankSection("unknown1790", 1790),

            // Forge labels — H2A StringID ref is 8 bits (Reach: 7).
            new CountSection(
                Name: "Labels",
                CountBits: 5,
                TableKey: "Gametype/base/mpvr/Labels",
                NameFromField: "StringID",
                RecordFields: new MegaloSection[]
                {
                    new StringTableRefSection("StringID", 8),
                    new VariantSection("usenumber", 1, new (int, string, MegaloSection[])[]
                    {
                        (0, "Null",   Array.Empty<MegaloSection>()),
                        (1, "InUse",  new MegaloSection[] { new SIntSection("Number", 16) }),
                    }),
                    new VariantSection("useteamtype", 1, new (int, string, MegaloSection[])[]
                    {
                        (0, "Null",   Array.Empty<MegaloSection>()),
                        (1, "InUse",  new MegaloSection[] { new UIntSection("Team", 4) }),
                    }),
                    new VariantSection("useobjectype", 1, new (int, string, MegaloSection[])[]
                    {
                        (0, "Null",   Array.Empty<MegaloSection>()),
                        (1, "InUse",  new MegaloSection[] { new UIntSection("Objecttype", 12) }),
                    }),
                    new UIntSection("MapMinimum", 7),
                }),

            // H2A adds an ObjectFilters block after Labels.
            new UIntSection("ObjectFiltersFakecount", 3),
            new CountSection("ObjectFilters", 3, new MegaloSection[]
            {
                new UIntSection("StringIDorLabelID", 8),
                new BlankSection("Unknown25", 25),
            }),

            // WeaponTunings — two back-to-back containers in H2A:
            //   Weapontunings  : 45 FiringProperties refs
            //   Weapontunings2 : 45 WeaponProperties refs
            // Each inner ref is an offset-based bit stream whose structure
            // hasn't been round-tripped against stock .bin.
            new UnverifiedSection(
                "H2A_WeaponTunings",
                "45 FiringProperties + 45 WeaponProperties ref blocks. "
                + "Each child uses offset-addressed 1-bit override flags "
                + "with 16/20/7-bit payloads — needs empirical width "
                + "verification against stock weapon-tuning .bin."),
        };

        // Full mpvr layout = mpvr FileHeader + shared body.
        private static MegaloSection[] BuildH2AMpvrLayout()
        {
            var body = BuildH2ABodyAfterHeader();
            var layout = new MegaloSection[H2AMpvrFileHeader().Length + body.Length];
            int i = 0;
            foreach (var s in H2AMpvrFileHeader()) layout[i++] = s;
            foreach (var s in body)               layout[i++] = s;
            return layout;
        }

        // Full gvar (forge variant) layout = gvar FileHeader + shared body.
        private static MegaloSection[] BuildH2AGvarLayout()
        {
            var body = BuildH2ABodyAfterHeader();
            var layout = new MegaloSection[H2AGvarFileHeader().Length + body.Length];
            int i = 0;
            foreach (var s in H2AGvarFileHeader()) layout[i++] = s;
            foreach (var s in body)               layout[i++] = s;
            return layout;
        }
    }
}
